/**
 * Copyright 2026 Arm Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as assert from 'assert';
import * as fs from 'fs';
import * as path from 'path';
import {
    SKILL_CATEGORY_ORDER,
    SkillCatalog,
    SkillCatalogEntry,
    bundledSkillNames,
    extractSkillReferences,
    groupByCategory,
    hasPackSkillSelected,
    loadSkillCatalog,
    parseSkillFrontmatter,
    resolveDesiredSkills,
} from '../utils/skillCatalog';
import {
    HELP_SKILL_NAME,
    HelpSkillConfig,
    readPackageContributions,
    renderHelpOpenAiYaml,
    renderHelpSkillMarkdown,
} from '../utils/skillHelp';
import { hashTree } from '../utils/treeHash';

/**
 * `skills/catalog.json` is generated by `npm run skills:sync` and shipped in
 * the VSIX; the runtime trusts it blindly. These tests pin the catalog to
 * the directories actually on disk and the lock file, so a hand edit to a
 * vendored skill, a forgotten re-sync after changing the generator config,
 * or a router description over the Agent Skills limit fails here rather
 * than in someone else's harness.
 */
suite('Agent skill catalog', () => {

    const repoRoot = path.resolve(__dirname, '..', '..', '..');
    const skillsDir = path.join(repoRoot, 'skills');
    const vendorDir = path.join(skillsDir, 'cmsis-agent');
    const lockPath = path.join(skillsDir, 'cmsis-agent.lock.json');

    const catalog = (): SkillCatalog => loadSkillCatalog(repoRoot);
    const lock = (): { sha: string; contentHash: string; repository: string } =>
        JSON.parse(fs.readFileSync(lockPath, 'utf8'));

    test('the catalog and the lock file ship alongside the extension', () => {
        assert.ok(fs.existsSync(path.join(skillsDir, 'catalog.json')));
        assert.ok(fs.existsSync(lockPath));
        assert.strictEqual(catalog().schemaVersion, 1);
    });

    test('the catalog is pinned to the same upstream commit as the lock', () => {
        assert.match(lock().sha, /^[0-9a-f]{40}$/);
        assert.strictEqual(catalog().source.sha, lock().sha);
        assert.strictEqual(catalog().source.repository, lock().repository);
    });

    test('every vendored skill directory is in the catalog and vice versa', () => {
        const onDisk = fs.readdirSync(vendorDir, { withFileTypes: true })
            .filter(entry => entry.isDirectory())
            .map(entry => entry.name)
            .sort();
        const inCatalog = catalog().skills
            .filter(entry => entry.source === 'cmsis-agent')
            .map(entry => entry.name)
            .sort();
        assert.deepStrictEqual(inCatalog, onDisk,
            'run `npm run skills:sync` — skills/cmsis-agent and skills/catalog.json disagree');
        assert.ok(onDisk.length > 0, 'no upstream skills vendored');
    });

    test('the vendored tree has not been edited by hand', () => {
        assert.strictEqual(hashTree(vendorDir), lock().contentHash,
            'skills/cmsis-agent differs from what `npm run skills:sync` wrote — re-sync instead of editing vendored files');
    });

    test('the upstream licence ships with the vendored skills', () => {
        const license = fs.readFileSync(path.join(vendorDir, 'LICENSE'), 'utf8');
        assert.match(license, /Apache License/);
    });

    test('every entry points at a real SKILL.md whose frontmatter agrees with the catalog', () => {
        for (const entry of catalog().skills) {
            const skillFile = path.join(repoRoot, entry.path, 'SKILL.md');
            assert.ok(fs.existsSync(skillFile), `${entry.name}: missing ${skillFile}`);
            assert.strictEqual(path.basename(entry.path), entry.name, `${entry.name}: directory name must equal the skill name`);
            const frontmatter = parseSkillFrontmatter(fs.readFileSync(skillFile, 'utf8'));
            assert.ok(frontmatter, `${entry.name}: unparseable frontmatter`);
            assert.strictEqual(frontmatter.name, entry.name);
            assert.strictEqual(frontmatter.description, entry.description);
        }
    });

    test('names are unique and categories are known', () => {
        const names = catalog().skills.map(entry => entry.name);
        assert.strictEqual(new Set(names).size, names.length, 'duplicate skill names');
        for (const entry of catalog().skills) {
            assert.ok(SKILL_CATEGORY_ORDER.includes(entry.category), `${entry.name}: unknown category ${entry.category}`);
        }
    });

    test('the bundled entries are the debugging skill and the help skill, nothing else', () => {
        const bundled = catalog().skills.filter(entry => entry.source === 'bundled');
        assert.deepStrictEqual(bundled.map(entry => [entry.name, entry.category, entry.path]), [
            ['cmsis-debug-live', 'debug', 'skills/cmsis-debug-live'],
            [HELP_SKILL_NAME, 'help', `skills/${HELP_SKILL_NAME}`],
        ]);
        assert.deepStrictEqual(bundledSkillNames(catalog()), ['cmsis-debug-live', HELP_SKILL_NAME]);
    });

    test('every dependency resolves to a catalog skill and nothing depends on itself', () => {
        const names = new Set(catalog().skills.map(entry => entry.name));
        for (const entry of catalog().skills) {
            for (const dependency of entry.dependsOn) {
                assert.ok(names.has(dependency), `${entry.name} depends on unknown ${dependency}`);
                assert.notStrictEqual(dependency, entry.name, `${entry.name} depends on itself`);
            }
        }
    });

    test('the $name references in each vendored SKILL.md are recorded as dependencies', () => {
        const names = new Set(catalog().skills.map(entry => entry.name));
        for (const entry of catalog().skills.filter(e => e.source === 'cmsis-agent')) {
            const markdown = fs.readFileSync(path.join(repoRoot, entry.path, 'SKILL.md'), 'utf8');
            const expected = extractSkillReferences(markdown).filter(ref => names.has(ref) && ref !== entry.name);
            assert.deepStrictEqual([...entry.dependsOn].sort(), expected,
                `${entry.name}: dependsOn is out of date — run \`npm run skills:sync\``);
        }
    });

    suite('routers', () => {
        const routers = (): SkillCatalogEntry[] => catalog().skills.filter(entry => entry.kind === 'router');

        test('one router per category that has upstream skills', () => {
            const categoriesWithSkills = new Set(catalog().skills
                .filter(entry => entry.source === 'cmsis-agent')
                .map(entry => entry.category));
            assert.deepStrictEqual(
                routers().map(router => router.category).sort(),
                [...categoriesWithSkills].sort());
        });

        test('a router depends on exactly the skills of its category', () => {
            for (const router of routers()) {
                const members = catalog().skills
                    .filter(entry => entry.kind === 'skill' && entry.category === router.category && entry.source === 'cmsis-agent')
                    .map(entry => entry.name)
                    .sort();
                assert.deepStrictEqual([...router.dependsOn].sort(), members, `${router.name}`);
            }
        });

        test('router descriptions respect the Agent Skills 1024-character limit', () => {
            for (const router of routers()) {
                assert.ok(router.description.length <= 1024,
                    `${router.name}: description is ${router.description.length} chars`);
            }
        });

        test('a router names every member and hands over by sibling path', () => {
            for (const router of routers()) {
                const markdown = fs.readFileSync(path.join(repoRoot, router.path, 'SKILL.md'), 'utf8');
                for (const member of router.dependsOn) {
                    assert.ok(markdown.includes(`\`$${member}\``), `${router.name} does not mention $${member}`);
                }
                assert.ok(markdown.includes('../<name>/SKILL.md'), `${router.name} must explain where the members live`);
                assert.ok(fs.existsSync(path.join(repoRoot, router.path, 'agents', 'openai.yaml')), `${router.name} has no Codex metadata`);
            }
        });

        test('router frontmatter is parseable YAML-wise: quoted description', () => {
            // A ": " inside an unquoted description is a YAML mapping and breaks
            // strict parsers; the generator must double-quote it.
            for (const router of routers()) {
                const markdown = fs.readFileSync(path.join(repoRoot, router.path, 'SKILL.md'), 'utf8');
                assert.match(markdown, /^description: "/m, `${router.name}`);
            }
        });

        test('every router points at the help skill for the full command list', () => {
            for (const router of routers()) {
                const markdown = fs.readFileSync(path.join(repoRoot, router.path, 'SKILL.md'), 'utf8');
                assert.ok(markdown.includes(`\`/${HELP_SKILL_NAME}\``), `${router.name} does not mention /${HELP_SKILL_NAME}`);
            }
        });
    });

    /**
     * The help skill is what an agent answers "what can I ask for?" from. It
     * is generated from the catalog, package.json and the generator config,
     * and re-rendered here: a new command, setting or skill that is not
     * reflected in the shipped file fails this suite, not a user's question.
     */
    suite(HELP_SKILL_NAME, () => {
        const helpDir = path.join(skillsDir, HELP_SKILL_NAME);
        const config = (): HelpSkillConfig =>
            JSON.parse(fs.readFileSync(path.join(repoRoot, 'scripts', 'skills.config.json'), 'utf8')).help;
        const contributions = () =>
            readPackageContributions(JSON.parse(fs.readFileSync(path.join(repoRoot, 'package.json'), 'utf8')));
        const shipped = (): string => fs.readFileSync(path.join(helpDir, 'SKILL.md'), 'utf8');

        test('the shipped SKILL.md and openai.yaml are exactly what the generator renders now', () => {
            assert.strictEqual(shipped(), renderHelpSkillMarkdown(catalog(), contributions(), config()),
                `skills/${HELP_SKILL_NAME}/SKILL.md is stale — run \`npm run skills:sync\``);
            assert.strictEqual(fs.readFileSync(path.join(helpDir, 'agents', 'openai.yaml'), 'utf8'), renderHelpOpenAiYaml(config()));
        });

        test('it is bundled, always installed, and its frontmatter is the config description, quoted', () => {
            const entry = catalog().skills.find(skill => skill.name === HELP_SKILL_NAME);
            assert.ok(entry);
            assert.strictEqual(entry.source, 'bundled');
            assert.deepStrictEqual(entry.dependsOn, [], 'the help skill must not pull the pack in');
            assert.strictEqual(entry.description, config().description);
            assert.ok(config().description.length <= 1024);
            assert.match(shipped(), /^description: "/m);
        });

        test('it names every slash command, every router member, every palette command and every listed setting', () => {
            const markdown = shipped();
            for (const entry of catalog().skills.filter(skill => skill.kind === 'router' || skill.source === 'bundled')) {
                assert.ok(markdown.includes(`\`/${entry.name}\``), `missing /${entry.name}`);
            }
            for (const router of catalog().skills.filter(skill => skill.kind === 'router')) {
                for (const member of router.dependsOn) {
                    assert.ok(markdown.includes(`\`$${member}\``), `missing $${member}`);
                }
            }
            for (const command of contributions().commands) {
                assert.ok(markdown.includes(command.title), `missing command title ${command.title}`);
                assert.ok(markdown.includes(`\`${command.command}\``), `missing command id ${command.command}`);
            }
            for (const hidden of contributions().hiddenCommands) {
                assert.ok(!markdown.includes(hidden), `hidden command ${hidden} must not be advertised`);
            }
            for (const id of Object.keys(config().settings)) {
                assert.ok(markdown.includes(`\`cmsis-developer-assistant.${id}\``), `missing setting ${id}`);
            }
            assert.ok(contributions().commands.length >= 2, 'palette commands disappeared');
        });

        test('every palette command needs a one-liner in the generator config, and vice versa', () => {
            const ids = contributions().commands.map(command => command.command).sort();
            assert.deepStrictEqual(Object.keys(config().settings).length > 0, true);
            assert.deepStrictEqual(Object.keys(config().commands).sort(), ids,
                'scripts/skills.config.json help.commands must list exactly the palette commands');
            const broken = { ...config(), commands: { ...config().commands, 'cmsis-developer-assistant.ghost': 'x' } };
            assert.throws(() => renderHelpSkillMarkdown(catalog(), contributions(), broken), /ghost/);
            const missing = { ...config(), settings: { ...config().settings, 'noSuchSetting': 'x' } };
            assert.throws(() => renderHelpSkillMarkdown(catalog(), contributions(), missing), /noSuchSetting/);
        });
    });

    suite('resolveDesiredSkills', () => {
        const fake: SkillCatalog = {
            schemaVersion: 1,
            source: { repository: 'r', sha: 'abc', sourcePath: 'p' },
            skills: [
                { name: 'r-pack', description: '', category: 'pack', kind: 'router', source: 'generated', path: 'skills/r-pack', dependsOn: ['gen', 'val'] },
                { name: 'gen', description: '', category: 'pack', kind: 'skill', source: 'cmsis-agent', path: 'skills/cmsis-agent/gen', dependsOn: ['know', 'val'] },
                { name: 'val', description: '', category: 'pack', kind: 'skill', source: 'cmsis-agent', path: 'skills/cmsis-agent/val', dependsOn: [] },
                { name: 'know', description: '', category: 'bring-up', kind: 'skill', source: 'cmsis-agent', path: 'skills/cmsis-agent/know', dependsOn: ['docs', 'know2'] },
                { name: 'know2', description: '', category: 'bring-up', kind: 'skill', source: 'cmsis-agent', path: 'skills/cmsis-agent/know2', dependsOn: ['know'] },
                { name: 'docs', description: '', category: 'bring-up', kind: 'skill', source: 'cmsis-agent', path: 'skills/cmsis-agent/docs', dependsOn: [] },
                { name: 'cmsis-debug-live', description: '', category: 'debug', kind: 'skill', source: 'bundled', path: 'skills/cmsis-debug-live', dependsOn: [] },
                { name: 'cmsis-help', description: '', category: 'help', kind: 'skill', source: 'bundled', path: 'skills/cmsis-help', dependsOn: [] },
            ],
        };
        const bundled = ['cmsis-debug-live', 'cmsis-help'];

        test('an empty selection still installs the bundled skills, and nothing else', () => {
            assert.deepStrictEqual(resolveDesiredSkills(fake, []), { explicit: bundled, implied: [], unknown: [], suppressed: [] });
        });

        test('a pre-2.3.2 selection that names the bundled skill is accepted and dedupes', () => {
            const desired = resolveDesiredSkills(fake, ['cmsis-debug-live']);
            assert.deepStrictEqual(desired, { explicit: bundled, implied: [], unknown: [], suppressed: [] });
        });

        test('picking a router implies its members and their transitive dependencies', () => {
            const desired = resolveDesiredSkills(fake, ['r-pack']);
            assert.deepStrictEqual(desired.explicit, ['r-pack', ...bundled]);
            assert.deepStrictEqual([...desired.implied].sort(), ['docs', 'gen', 'know', 'know2', 'val']);
        });

        test('explicit picks are never listed as implied, cycles terminate', () => {
            const desired = resolveDesiredSkills(fake, ['know', 'know2']);
            assert.deepStrictEqual(desired.explicit, ['know', 'know2', ...bundled]);
            assert.deepStrictEqual(desired.implied, ['docs']);
        });

        test('unknown names are reported, not thrown, and duplicates collapse', () => {
            const desired = resolveDesiredSkills(fake, ['val', 'from-the-future', 'val', 'from-the-future']);
            assert.deepStrictEqual(desired.explicit, ['val', ...bundled]);
            assert.deepStrictEqual(desired.unknown, ['from-the-future']);
        });

        test('with the pack disabled only the bundled skills are desired and the picks are reported as suppressed', () => {
            const desired = resolveDesiredSkills(fake, ['r-pack', 'know', 'cmsis-debug-live', 'from-the-future'], { packEnabled: false });
            assert.deepStrictEqual(desired.explicit, bundled);
            assert.deepStrictEqual(desired.implied, [], 'pack members must not sneak in through the closure');
            assert.deepStrictEqual(desired.suppressed, ['r-pack', 'know']);
            assert.deepStrictEqual(desired.unknown, ['from-the-future']);
        });

        test('hasPackSkillSelected sees routers and members, not bundled or unknown names', () => {
            assert.strictEqual(hasPackSkillSelected(fake, []), false);
            assert.strictEqual(hasPackSkillSelected(fake, ['cmsis-debug-live', 'from-the-future']), false);
            assert.strictEqual(hasPackSkillSelected(fake, ['r-pack']), true);
            assert.strictEqual(hasPackSkillSelected(fake, ['cmsis-debug-live', 'docs']), true);
        });

        test('groupByCategory orders categories and puts the router first', () => {
            const groups = groupByCategory(fake);
            assert.deepStrictEqual([...groups.keys()], ['bring-up', 'debug', 'pack', 'help']);
            assert.deepStrictEqual(groups.get('pack')?.map(entry => entry.name), ['r-pack', 'gen', 'val']);
        });
    });

    suite('frontmatter parsing', () => {
        test('reads plain and double-quoted scalars', () => {
            const plain = parseSkillFrontmatter('---\nname: a\ndescription: Do the thing. Use when asked.\n---\n# A\n');
            assert.deepStrictEqual([plain?.name, plain?.description], ['a', 'Do the thing. Use when asked.']);
            const quoted = parseSkillFrontmatter('---\nname: b\ndescription: "Build: a record, \\"verified\\"."\nlicense: MIT\n---\n');
            assert.strictEqual(quoted?.description, 'Build: a record, "verified".');
        });

        test('tolerates CRLF and rejects files without a fence', () => {
            assert.strictEqual(parseSkillFrontmatter('---\r\nname: c\r\ndescription: d\r\n---\r\nbody')?.name, 'c');
            assert.strictEqual(parseSkillFrontmatter('# no frontmatter\n'), null);
        });

        test('extracts $name references, lowercase-hyphenated only', () => {
            const refs = extractSkillReferences('after `$debug-knowledge` and $trace-knowledge; not $HOME, not ${var}, not $a.');
            assert.deepStrictEqual(refs, ['debug-knowledge', 'trace-knowledge']);
        });
    });
});
