// Copyright (c) Microsoft Corporation.
// Copyright 2026 Arm Limited and contributors

import * as assert from 'assert';
import * as fs from 'fs';
import * as path from 'path';
import {
    SKILL_CATEGORY_ORDER,
    SkillCatalog,
    SkillCatalogEntry,
    extractSkillReferences,
    groupByCategory,
    loadSkillCatalog,
    parseSkillFrontmatter,
    resolveDesiredSkills,
} from '../utils/skillCatalog';
import { hashTree } from '../utils/treeHash';

/**
 * `skills/catalog.json` is generated by `npm run skills:sync` and shipped in
 * the VSIX; the runtime trusts it blindly. These tests pin the catalog to
 * the directories actually on disk and the lock file, so a hand edit to a
 * vendored skill, a forgotten re-sync after changing the generator config,
 * or a router description over the Agent Skills limit fails here rather
 * than in someone else's harness.
 */
suite('Agent skill catalog', () => {

    const repoRoot = path.resolve(__dirname, '..', '..', '..');
    const skillsDir = path.join(repoRoot, 'skills');
    const vendorDir = path.join(skillsDir, 'cmsis-agent');
    const lockPath = path.join(skillsDir, 'cmsis-agent.lock.json');

    const catalog = (): SkillCatalog => loadSkillCatalog(repoRoot);
    const lock = (): { sha: string; contentHash: string; repository: string } =>
        JSON.parse(fs.readFileSync(lockPath, 'utf8'));

    test('the catalog and the lock file ship alongside the extension', () => {
        assert.ok(fs.existsSync(path.join(skillsDir, 'catalog.json')));
        assert.ok(fs.existsSync(lockPath));
        assert.strictEqual(catalog().schemaVersion, 1);
    });

    test('the catalog is pinned to the same upstream commit as the lock', () => {
        assert.match(lock().sha, /^[0-9a-f]{40}$/);
        assert.strictEqual(catalog().source.sha, lock().sha);
        assert.strictEqual(catalog().source.repository, lock().repository);
    });

    test('every vendored skill directory is in the catalog and vice versa', () => {
        const onDisk = fs.readdirSync(vendorDir, { withFileTypes: true })
            .filter(entry => entry.isDirectory())
            .map(entry => entry.name)
            .sort();
        const inCatalog = catalog().skills
            .filter(entry => entry.source === 'cmsis-agent')
            .map(entry => entry.name)
            .sort();
        assert.deepStrictEqual(inCatalog, onDisk,
            'run `npm run skills:sync` — skills/cmsis-agent and skills/catalog.json disagree');
        assert.ok(onDisk.length > 0, 'no upstream skills vendored');
    });

    test('the vendored tree has not been edited by hand', () => {
        assert.strictEqual(hashTree(vendorDir), lock().contentHash,
            'skills/cmsis-agent differs from what `npm run skills:sync` wrote — re-sync instead of editing vendored files');
    });

    test('the upstream licence ships with the vendored skills', () => {
        const license = fs.readFileSync(path.join(vendorDir, 'LICENSE'), 'utf8');
        assert.match(license, /Apache License/);
    });

    test('every entry points at a real SKILL.md whose frontmatter agrees with the catalog', () => {
        for (const entry of catalog().skills) {
            const skillFile = path.join(repoRoot, entry.path, 'SKILL.md');
            assert.ok(fs.existsSync(skillFile), `${entry.name}: missing ${skillFile}`);
            assert.strictEqual(path.basename(entry.path), entry.name, `${entry.name}: directory name must equal the skill name`);
            const frontmatter = parseSkillFrontmatter(fs.readFileSync(skillFile, 'utf8'));
            assert.ok(frontmatter, `${entry.name}: unparseable frontmatter`);
            assert.strictEqual(frontmatter.name, entry.name);
            assert.strictEqual(frontmatter.description, entry.description);
        }
    });

    test('names are unique and categories are known', () => {
        const names = catalog().skills.map(entry => entry.name);
        assert.strictEqual(new Set(names).size, names.length, 'duplicate skill names');
        for (const entry of catalog().skills) {
            assert.ok(SKILL_CATEGORY_ORDER.includes(entry.category), `${entry.name}: unknown category ${entry.category}`);
        }
    });

    test('the bundled debugging skill is the default and the only bundled entry', () => {
        const bundled = catalog().skills.filter(entry => entry.source === 'bundled');
        assert.deepStrictEqual(bundled.map(entry => entry.name), ['cmsis-debug-live']);
        assert.strictEqual(bundled[0].category, 'debug');
        assert.strictEqual(bundled[0].path, 'skills/cmsis-debug-live');
    });

    test('every dependency resolves to a catalog skill and nothing depends on itself', () => {
        const names = new Set(catalog().skills.map(entry => entry.name));
        for (const entry of catalog().skills) {
            for (const dependency of entry.dependsOn) {
                assert.ok(names.has(dependency), `${entry.name} depends on unknown ${dependency}`);
                assert.notStrictEqual(dependency, entry.name, `${entry.name} depends on itself`);
            }
        }
    });

    test('the $name references in each vendored SKILL.md are recorded as dependencies', () => {
        const names = new Set(catalog().skills.map(entry => entry.name));
        for (const entry of catalog().skills.filter(e => e.source === 'cmsis-agent')) {
            const markdown = fs.readFileSync(path.join(repoRoot, entry.path, 'SKILL.md'), 'utf8');
            const expected = extractSkillReferences(markdown).filter(ref => names.has(ref) && ref !== entry.name);
            assert.deepStrictEqual([...entry.dependsOn].sort(), expected,
                `${entry.name}: dependsOn is out of date — run \`npm run skills:sync\``);
        }
    });

    suite('routers', () => {
        const routers = (): SkillCatalogEntry[] => catalog().skills.filter(entry => entry.kind === 'router');

        test('one router per category that has upstream skills', () => {
            const categoriesWithSkills = new Set(catalog().skills
                .filter(entry => entry.source === 'cmsis-agent')
                .map(entry => entry.category));
            assert.deepStrictEqual(
                routers().map(router => router.category).sort(),
                [...categoriesWithSkills].sort());
        });

        test('a router depends on exactly the skills of its category', () => {
            for (const router of routers()) {
                const members = catalog().skills
                    .filter(entry => entry.kind === 'skill' && entry.category === router.category && entry.source === 'cmsis-agent')
                    .map(entry => entry.name)
                    .sort();
                assert.deepStrictEqual([...router.dependsOn].sort(), members, `${router.name}`);
            }
        });

        test('router descriptions respect the Agent Skills 1024-character limit', () => {
            for (const router of routers()) {
                assert.ok(router.description.length <= 1024,
                    `${router.name}: description is ${router.description.length} chars`);
            }
        });

        test('a router names every member and hands over by sibling path', () => {
            for (const router of routers()) {
                const markdown = fs.readFileSync(path.join(repoRoot, router.path, 'SKILL.md'), 'utf8');
                for (const member of router.dependsOn) {
                    assert.ok(markdown.includes(`\`$${member}\``), `${router.name} does not mention $${member}`);
                }
                assert.ok(markdown.includes('../<name>/SKILL.md'), `${router.name} must explain where the members live`);
                assert.ok(fs.existsSync(path.join(repoRoot, router.path, 'agents', 'openai.yaml')), `${router.name} has no Codex metadata`);
            }
        });

        test('router frontmatter is parseable YAML-wise: quoted description', () => {
            // A ": " inside an unquoted description is a YAML mapping and breaks
            // strict parsers; the generator must double-quote it.
            for (const router of routers()) {
                const markdown = fs.readFileSync(path.join(repoRoot, router.path, 'SKILL.md'), 'utf8');
                assert.match(markdown, /^description: "/m, `${router.name}`);
            }
        });
    });

    suite('resolveDesiredSkills', () => {
        const fake: SkillCatalog = {
            schemaVersion: 1,
            source: { repository: 'r', sha: 'abc', sourcePath: 'p' },
            skills: [
                { name: 'r-pack', description: '', category: 'pack', kind: 'router', source: 'generated', path: 'skills/r-pack', dependsOn: ['gen', 'val'] },
                { name: 'gen', description: '', category: 'pack', kind: 'skill', source: 'cmsis-agent', path: 'skills/cmsis-agent/gen', dependsOn: ['know', 'val'] },
                { name: 'val', description: '', category: 'pack', kind: 'skill', source: 'cmsis-agent', path: 'skills/cmsis-agent/val', dependsOn: [] },
                { name: 'know', description: '', category: 'bring-up', kind: 'skill', source: 'cmsis-agent', path: 'skills/cmsis-agent/know', dependsOn: ['docs', 'know2'] },
                { name: 'know2', description: '', category: 'bring-up', kind: 'skill', source: 'cmsis-agent', path: 'skills/cmsis-agent/know2', dependsOn: ['know'] },
                { name: 'docs', description: '', category: 'bring-up', kind: 'skill', source: 'cmsis-agent', path: 'skills/cmsis-agent/docs', dependsOn: [] },
                { name: 'cmsis-debug-live', description: '', category: 'debug', kind: 'skill', source: 'bundled', path: 'skills/cmsis-debug-live', dependsOn: [] },
            ],
        };

        test('the default selection is just the bundled skill', () => {
            const desired = resolveDesiredSkills(fake, ['cmsis-debug-live']);
            assert.deepStrictEqual(desired, { explicit: ['cmsis-debug-live'], implied: [], unknown: [] });
        });

        test('picking a router implies its members and their transitive dependencies', () => {
            const desired = resolveDesiredSkills(fake, ['r-pack']);
            assert.deepStrictEqual(desired.explicit, ['r-pack']);
            assert.deepStrictEqual([...desired.implied].sort(), ['docs', 'gen', 'know', 'know2', 'val']);
        });

        test('explicit picks are never listed as implied, cycles terminate', () => {
            const desired = resolveDesiredSkills(fake, ['know', 'know2']);
            assert.deepStrictEqual(desired.explicit, ['know', 'know2']);
            assert.deepStrictEqual(desired.implied, ['docs']);
        });

        test('unknown names are reported, not thrown, and duplicates collapse', () => {
            const desired = resolveDesiredSkills(fake, ['val', 'from-the-future', 'val', 'from-the-future']);
            assert.deepStrictEqual(desired.explicit, ['val']);
            assert.deepStrictEqual(desired.unknown, ['from-the-future']);
        });

        test('an empty selection installs nothing', () => {
            assert.deepStrictEqual(resolveDesiredSkills(fake, []), { explicit: [], implied: [], unknown: [] });
        });

        test('groupByCategory orders categories and puts the router first', () => {
            const groups = groupByCategory(fake);
            assert.deepStrictEqual([...groups.keys()], ['bring-up', 'debug', 'pack']);
            assert.deepStrictEqual(groups.get('pack')?.map(entry => entry.name), ['r-pack', 'gen', 'val']);
        });
    });

    suite('frontmatter parsing', () => {
        test('reads plain and double-quoted scalars', () => {
            const plain = parseSkillFrontmatter('---\nname: a\ndescription: Do the thing. Use when asked.\n---\n# A\n');
            assert.deepStrictEqual([plain?.name, plain?.description], ['a', 'Do the thing. Use when asked.']);
            const quoted = parseSkillFrontmatter('---\nname: b\ndescription: "Build: a record, \\"verified\\"."\nlicense: MIT\n---\n');
            assert.strictEqual(quoted?.description, 'Build: a record, "verified".');
        });

        test('tolerates CRLF and rejects files without a fence', () => {
            assert.strictEqual(parseSkillFrontmatter('---\r\nname: c\r\ndescription: d\r\n---\r\nbody')?.name, 'c');
            assert.strictEqual(parseSkillFrontmatter('# no frontmatter\n'), null);
        });

        test('extracts $name references, lowercase-hyphenated only', () => {
            const refs = extractSkillReferences('after `$debug-knowledge` and $trace-knowledge; not $HOME, not ${var}, not $a.');
            assert.deepStrictEqual(refs, ['debug-knowledge', 'trace-knowledge']);
        });
    });
});
