# Copyright 2026 Arm Limited
# Licensed under the Apache License, Version 2.0; see gen_core_svd.py.
"""Implementation-specific blocks: the Cortex-M7 TCM/cache/AHB control registers in the SCB, and the
Cortex-M55/M85/M52 memory system, power mode, EWIC, error bank, configuration info, STL and DCAR blocks,
plus the STAR-MC1 EMSS. Condensed from the Cortex-M7 (DDI0489), Cortex-M55 (101051), Cortex-M85 (101924)
and Cortex-M52 (102776) TRMs."""

PERIPHERAL_DESC = {
    'ERRBNK': 'Error Bank: records the location of ECC errors detected in the instruction cache, data cache and (Cortex-M55/M85) TCM RAMs, so software can '
              'scrub the location and diagnose failing RAM.',
    'MEMSYSCTL': 'Memory System Control (Cortex-M55/M85/M52): ECC, cache and prefetcher control, TCM and P-AHB window enables, and the TCM Gate Units '
                 '(ITGU/DTGU) that assign security attributes to TCM blocks.',
    'PWRMODCTL': 'Power Mode Control (Cortex-M55/M85/M52): the low-power state (ON / retention / OFF) requested for the core, EPU and RAM power domains when the processor sleeps.',
    'EWIC': 'External Wakeup Interrupt Controller: latches interrupt, NMI and event inputs while the processor is powered down and wakes it. Configure the masks before sleeping.',
    'EWIC_ISA': 'EWIC Interrupt Status Access: the processor-side view of the EWIC — set an event pending and read back the mask configuration.',
    'PRCCFGINF': 'Processor Configuration Information: indexed read access to the build-time configuration of the core (cache/TCM sizes, options).',
    'STL': 'Software Test Library support registers (Cortex-M55/M85): expose internal NVIC priority-tree, MPU lookup, store buffer and line-fill state for functional-safety self test.',
    'DCAR': 'Direct Cache Access Registers (Cortex-M52): read cache RAM contents by location for test and diagnostics.',
    'EMSS': 'Embedded Memory Subsystem control (STAR-MC1): L1 cache control and the ITCM/DTCM enables and sizes.',
}

REGISTER_DESC = {
    'SCB.ITCMCR': 'Instruction TCM Control Register (Cortex-M7): enable, read-modify-write and retry modes, and the size of the ITCM at 0x00000000.',
    'SCB.DTCMCR': 'Data TCM Control Register (Cortex-M7): enable, read-modify-write and retry modes, and the size of the DTCM at 0x20000000.',
    'SCB.AHBPCR': 'AHBP Control Register (Cortex-M7): enable and size of the AHB peripheral port window in the Peripheral region.',
    'SCB.CACR': 'L1 Cache Control Register (Cortex-M7): shared-is-write-through, ECC and forced write-through.',
    'SCB.AHBSCR': 'AHB Slave Control Register (Cortex-M7): arbitration between the core and the AHBS (DMA) port for TCM accesses.',
    'SCB.ABFSR': 'Auxiliary Bus Fault Status Register (Cortex-M7): which interface an asynchronous (imprecise) bus fault came from. Write 1 to clear.',
    'ERRBNK.IEBR0': 'Instruction Cache Error Bank Register 0: the first recorded I-cache ECC error.',
    'ERRBNK.IEBR1': 'Instruction Cache Error Bank Register 1: the second recorded I-cache ECC error.',
    'ERRBNK.DEBR0': 'Data Cache Error Bank Register 0: the first recorded D-cache ECC error.',
    'ERRBNK.DEBR1': 'Data Cache Error Bank Register 1: the second recorded D-cache ECC error.',
    'ERRBNK.TEBR0': 'TCM Error Bank Register 0: the first recorded TCM ECC error.',
    'ERRBNK.TEBR1': 'TCM Error Bank Register 1: the second recorded TCM ECC error.',
    'MEMSYSCTL.MSCR': 'Memory System Control Register: ECC enable, forced write-through, ECC fault reporting, TCM ECC checking and read-only cache status.',
    'MEMSYSCTL.PFCR': 'Prefetcher Control Register: data prefetcher enable and look-ahead/outstanding limits.',
    'MEMSYSCTL.ITCMCR': 'ITCM Control Register: enable and size of the instruction TCM.',
    'MEMSYSCTL.DTCMCR': 'DTCM Control Register: enable and size of the data TCM.',
    'MEMSYSCTL.PAHBCR': 'P-AHB Control Register: enable and size of the peripheral AHB window.',
    'MEMSYSCTL.ITGU_CTRL': 'ITCM Gate Unit Control Register: how ITGU security violations are reported.',
    'MEMSYSCTL.ITGU_CFG': 'ITCM Gate Unit Configuration Register: block size and count (read-only).',
    'MEMSYSCTL.ITGU_LUTn': 'ITCM Gate Unit Look-Up Table n: bit k marks ITCM block 32n+k as Non-secure (0 = Secure).',
    'MEMSYSCTL.DTGU_CTRL': 'DTCM Gate Unit Control Register: how DTGU security violations are reported.',
    'MEMSYSCTL.DTGU_CFG': 'DTCM Gate Unit Configuration Register: block size and count (read-only).',
    'MEMSYSCTL.DTGU_LUTn': 'DTCM Gate Unit Look-Up Table n: bit k marks DTCM block 32n+k as Non-secure (0 = Secure).',
    'PWRMODCTL.CPDLPSTATE': 'Core Power Domain Low Power State Register: the power state requested for the core, EPU (FPU/MVE) and RAM domains on deep sleep.',
    'PWRMODCTL.DPDLPSTATE': 'Debug Power Domain Low Power State Register: the power state requested for the debug domain.',
    'EWIC.EWIC_CR': 'EWIC Control Register: global enable.',
    'EWIC.EWIC_ASCR': 'EWIC Automatic Sequence Control Register: automatic mask/unmask sequencing on power-down and power-up.',
    'EWIC.EWIC_CLRMASK': 'EWIC Clear Mask Register: write to clear all mask registers.',
    'EWIC.EWIC_NUMID': 'EWIC Event Number ID Register: how many events (interrupts plus NMI/EVENT/EDBGREQ) the EWIC handles.',
    'EWIC.EWIC_MASKA': 'EWIC Mask A Register: wake-up enables for the non-interrupt events (EVENT, NMI, EDBGREQ).',
    'EWIC.EWIC_MASKn': 'EWIC Mask Register n: bit k enables wake-up on IRQ 32(n−1)+k.',
    'EWIC.EWIC_PENDA': 'EWIC Pend A Register: which non-interrupt events have been latched.',
    'EWIC.EWIC_PENDn': 'EWIC Pend Register n: bit k = IRQ 32(n−1)+k has been latched while the processor was powered down.',
    'EWIC.EWIC_PSR': 'EWIC Pend Summary Register: which PEND registers hold at least one latched event.',
    'EWIC_ISA.EVENTSPR': 'Event Set Pending Register: software writes to latch an event as if it had arrived.',
    'EWIC_ISA.EVENTMASKA': 'Event Mask A Register: read-only copy of EWIC_MASKA.',
    'EWIC_ISA.EVENTMASKn': 'Event Mask Register n: read-only copy of EWIC_MASKn.',
    'PRCCFGINF.CFGINFOSEL': 'Processor Configuration Information Selection Register: write the index of the configuration word to read from CFGINFORD.',
    'PRCCFGINF.CFGINFORD': 'Processor Configuration Information Read Data Register: the configuration word selected by CFGINFOSEL.',
    'STL.STLNVICPENDOR': 'NVIC Pending Priority Tree Register: the output of the NVIC pending-priority tree (highest-priority pending interrupt).',
    'STL.STLNVICACTVOR': 'NVIC Active Priority Tree Register: the output of the NVIC active-priority tree (highest-priority active interrupt).',
    'STL.STLIDMPUSR': 'MPU Sample Register: write an address and side to perform a test MPU lookup whose results appear in STLIMPUOR / STLDnMPUOR.',
    'STL.STLIMPUOR': 'MPU Region Hit Register: instruction-side result of the STLIDMPUSR lookup.',
    'STL.STLD0MPUOR': 'MPU Memory Attributes Register 0: data-side result of the STLIDMPUSR lookup (lookup 0).',
    'STL.STLD1MPUOR': 'MPU Memory Attributes Register 1: data-side result of the STLIDMPUSR lookup (lookup 1).',
    'STL.STLD2MPUOR': 'MPU Memory Attributes Register 2: data-side result of the STLIDMPUSR lookup (lookup 2).',
    'STL.STLD3MPUOR': 'MPU Memory Attributes Register 3: data-side result of the STLIDMPUSR lookup (lookup 3).',
    'STL.STLDMPUOR': 'MPU Memory Attributes Register: data-side result of the STLIDMPUSR lookup.',
    'STL.STLSTBSLOTSR': 'STB Control Register: selects a store buffer slot for test.',
    'STL.STLLFDENTRYSR': 'LFD Control Register: selects a line-fill data entry for test.',
    'DCAR.DCADCRR': 'Direct Cache Access Data Cache Read Register: the data read from the D-cache location selected in DCADCLR.',
    'DCAR.DCAICRR': 'Direct Cache Access Instruction Cache Read Register: the data read from the I-cache location selected in DCAICLR.',
    'DCAR.DCADCLR': 'Direct Cache Access Data Cache Location Register: set, way and word of the D-cache entry to read.',
    'DCAR.DCAICLR': 'Direct Cache Access Instruction Cache Location Register: set, way and word of the I-cache entry to read.',
    'EMSS.CACR': 'L1 Cache Control Register (STAR-MC1): forced write-through and cache status.',
    'EMSS.ITCMCR': 'ITCM Control Register (STAR-MC1): enable and size of the instruction TCM.',
    'EMSS.DTCMCR': 'DTCM Control Register (STAR-MC1): enable and size of the data TCM.',
}

_TCM_SZ = 'TCM size: 0 = none, 3 = 4 KB, 4 = 8 KB, 5 = 16 KB, 6 = 32 KB, 7 = 64 KB, 8 = 128 KB, 9 = 256 KB, 10 = 512 KB, 11 = 1 MB, 12 = 2 MB, 13 = 4 MB, 14 = 8 MB, 15 = 16 MB (2^(SZ−1) KB). Read-only.'
_PAHB_SZ = 'P-AHB window size: 0 = disabled, 1 = 64 MB, 2 = 128 MB, 3 = 256 MB, 4 = 512 MB. Read-only.'

FIELD_DESC = {
    # ── Cortex-M7 SCB extras ─────────────────────────────────────────────────
    'SCB.ITCMCR.EN': 'ITCM enable: 1 = the ITCM responds to accesses in its address range (0x00000000).',
    'SCB.ITCMCR.RMW': 'Read-modify-write enable: 1 = every sub-width write becomes a full-width read-modify-write (needed for correct ECC on narrow writes).',
    'SCB.ITCMCR.RETEN': 'Retry enable: 1 = an access that hit a correctable ECC error is retried after correction (r1p0+ with ECC).',
    'SCB.ITCMCR.SZ': _TCM_SZ,
    'SCB.DTCMCR.EN': 'DTCM enable: 1 = the DTCM responds to accesses in its address range (0x20000000).',
    'SCB.DTCMCR.RMW': 'Read-modify-write enable: 1 = every sub-width write becomes a full-width read-modify-write (needed for correct ECC on narrow writes).',
    'SCB.DTCMCR.RETEN': 'Retry enable: 1 = an access that hit a correctable ECC error is retried after correction.',
    'SCB.DTCMCR.SZ': _TCM_SZ,
    'SCB.AHBPCR.EN': 'AHBP enable: 1 = accesses to the AHBP window go out on the AHB peripheral port instead of the AXI master.',
    'SCB.AHBPCR.SZ': 'AHBP window size starting at 0x40000000: 0 = disabled, 1 = 64 MB, 2 = 128 MB, 3 = 256 MB, 4 = 512 MB. Read-only.',
    'SCB.CACR.SIWT': 'Shared cacheable-is-write-through: 1 = shareable Normal cacheable memory is cached write-through (0 = treated as non-cacheable), keeping DMA-visible buffers coherent for reads.',
    'SCB.CACR.ECCDIS': 'ECC disable: 1 = error detection and correction in the L1 caches is off.',
    'SCB.CACR.FORCEWT': 'Force write-through: 1 = all cacheable data is treated as write-through regardless of memory attributes.',
    'SCB.AHBSCR.CTL': 'AHBS prioritization: 0 = AHBS demoted after INITCOUNT consecutive accesses (round-robin fairness), 1 = core demoted after INITCOUNT, 2 = AHBS always has priority, 3 = core always has priority.',
    'SCB.AHBSCR.TPRI': 'Threshold execution priority: the fairness policy applies only while the current execution priority is numerically greater than or equal to TPRI (i.e. lower priority code).',
    'SCB.AHBSCR.INITCOUNT': 'Fairness counter initial value: how many consecutive accesses the prioritized master may make before yielding.',
    'SCB.ABFSR.ITCM': 'Asynchronous fault on the ITCM interface.',
    'SCB.ABFSR.DTCM': 'Asynchronous fault on the DTCM interface.',
    'SCB.ABFSR.AHBP': 'Asynchronous fault on the AHB peripheral port.',
    'SCB.ABFSR.AXIM': 'Asynchronous fault on the AXI master port (see AXIMTYPE).',
    'SCB.ABFSR.EPPB': 'Asynchronous fault on the external PPB (debug/CoreSight) interface.',
    'SCB.ABFSR.AXIMTYPE': 'AXIM fault type (the AXI response): 0 = OKAY, 1 = EXOKAY, 2 = SLVERR (slave error), 3 = DECERR (decode error — unmapped address).',
    # ── ERRBNK ───────────────────────────────────────────────────────────────
    'ERRBNK.IEBR.VALID': 'Entry valid: an error has been recorded. Clear it after scrubbing the location.',
    'ERRBNK.IEBR.LOCK': 'Locked: a further error occurred while this entry was valid; the entry keeps the first error until cleared.',
    'ERRBNK.IEBR.LOCKED': 'Locked: a further error occurred while this entry was valid; the entry keeps the first error until cleared.',
    'ERRBNK.IEBR.LDO': 'Cortex-M7 error bank bits [3:2]; see the error bank register layout in the Cortex-M7 TRM.',
    'ERRBNK.IEBR.INDEX': 'Cache set index of the error (Cortex-M7).',
    'ERRBNK.IEBR.WAY': 'Cache way of the error (Cortex-M7 2-way I-cache).',
    'ERRBNK.IEBR.RAMBank': 'RAM bank of the error (Cortex-M7).',
    'ERRBNK.IEBR.TYPE': 'Error type: 0 = data RAM, 1 = tag RAM.',
    'ERRBNK.IEBR.USER': 'Software-defined bits (not used by hardware).',
    'ERRBNK.IEBR.LOCATION': 'Location of the error inside the I-cache (set/way/word encoding, see the TRM).',
    'ERRBNK.IEBR.BANK': 'RAM bank of the error.',
    'ERRBNK.IEBR.SWDEF': 'Software-defined bits (not used by hardware).',
    'ERRBNK.DEBR.VALID': 'Entry valid: an error has been recorded.',
    'ERRBNK.DEBR.LOCK': 'Locked: a further error occurred while this entry was valid; the entry keeps the first error until cleared.',
    'ERRBNK.DEBR.LOCKED': 'Locked: a further error occurred while this entry was valid; the entry keeps the first error until cleared.',
    'ERRBNK.DEBR.LDO': 'Cortex-M7 error bank bits [3:2]; see the error bank register layout in the Cortex-M7 TRM.',
    'ERRBNK.DEBR.INDEX': 'Cache set index of the error (Cortex-M7).',
    'ERRBNK.DEBR.WAY': 'Cache way of the error.',
    'ERRBNK.DEBR.RAMBank': 'RAM bank of the error (Cortex-M7).',
    'ERRBNK.DEBR.TYPE': 'Error type: 0 = data RAM, 1 = tag/dirty RAM.',
    'ERRBNK.DEBR.USER': 'Software-defined bits (not used by hardware).',
    'ERRBNK.DEBR.LOCATION': 'Location of the error inside the D-cache (set/way/word encoding, see the TRM).',
    'ERRBNK.DEBR.BANK': 'RAM bank of the error.',
    'ERRBNK.DEBR.SWDEF': 'Software-defined bits (not used by hardware).',
    'ERRBNK.TEBR.VALID': 'Entry valid: an error has been recorded.',
    'ERRBNK.TEBR.LOCKED': 'Locked: a further error occurred while this entry was valid.',
    'ERRBNK.TEBR.LOCATION': 'Word address of the error within the TCM.',
    'ERRBNK.TEBR.BANK': 'TCM bank: which of the ITCM/DTCM RAM banks the error was in.',
    'ERRBNK.TEBR.TYPE': 'Error type: 0 = correctable (single-bit), 1 = uncorrectable (double-bit).',
    'ERRBNK.TEBR.POISON': '1 = the location was poisoned (its data marked invalid) after an uncorrectable error.',
    'ERRBNK.TEBR.SWDEF': 'Software-defined bits (not used by hardware).',
    # ── MEMSYSCTL ────────────────────────────────────────────────────────────
    'MEMSYSCTL.MSCR.ECCEN': 'ECC enable for the caches and TCMs.',
    'MEMSYSCTL.MSCR.FORCEWT': 'Force write-through: 1 = all cacheable data is cached write-through.',
    'MEMSYSCTL.MSCR.EVECCFAULT': 'Enable ECC fault reporting: 1 = an uncorrectable ECC error raises a BusFault (with an error bank entry) instead of being silently poisoned.',
    'MEMSYSCTL.MSCR.TECCCHKDIS': 'TCM ECC check disable: 1 = ECC on the TCMs is not checked (still generated).',
    'MEMSYSCTL.MSCR.DCACTIVE': 'Data cache active (read-only): 1 = the D-cache is enabled and powered.',
    'MEMSYSCTL.MSCR.ICACTIVE': 'Instruction cache active (read-only).',
    'MEMSYSCTL.MSCR.DCCLEAN': 'Data cache clean (read-only): 1 = no dirty lines.',
    'MEMSYSCTL.MSCR.CPWRDN': 'Cache power-down: 1 = the cache RAMs may be powered down when the caches are disabled.',
    'MEMSYSCTL.PFCR.ENABLE': 'Data prefetcher enable.',
    'MEMSYSCTL.PFCR.MIN_LA': 'Minimum look-ahead distance (cache lines).',
    'MEMSYSCTL.PFCR.MAX_LA': 'Maximum look-ahead distance (cache lines).',
    'MEMSYSCTL.PFCR.MAX_OS': 'Maximum number of outstanding prefetches.',
    'MEMSYSCTL.PFCR.DIS_NLP': 'Disable next-line prefetch (Cortex-M85).',
    'MEMSYSCTL.ITCMCR.EN': 'ITCM enable: 1 = the ITCM responds to accesses in its address range.',
    'MEMSYSCTL.ITCMCR.SZ': _TCM_SZ,
    'MEMSYSCTL.DTCMCR.EN': 'DTCM enable: 1 = the DTCM responds to accesses in its address range.',
    'MEMSYSCTL.DTCMCR.SZ': _TCM_SZ,
    'MEMSYSCTL.PAHBCR.EN': 'P-AHB enable: 1 = accesses in the P-AHB window use the peripheral AHB port instead of the AXI master.',
    'MEMSYSCTL.PAHBCR.SZ': _PAHB_SZ,
    'MEMSYSCTL.ITGU_CTRL.DBFEN': 'Data bus fault enable: 1 = an ITGU security violation raises a BusFault/SecureFault (0 = the access is RAZ/WI).',
    'MEMSYSCTL.ITGU_CTRL.DEREN': 'Debug error response enable: 1 = debugger accesses that violate the ITGU get an error response.',
    'MEMSYSCTL.ITGU_CFG.BLKSZ': 'Block size: 2^(BLKSZ+5) bytes per look-up-table bit.',
    'MEMSYSCTL.ITGU_CFG.NUMBLKS': 'Number of blocks: 2^NUMBLKS.',
    'MEMSYSCTL.ITGU_CFG.PRESENT': 'ITGU present.',
    'MEMSYSCTL.DTGU_CTRL.DBFEN': 'Data bus fault enable: 1 = a DTGU security violation raises a BusFault/SecureFault (0 = the access is RAZ/WI).',
    'MEMSYSCTL.DTGU_CTRL.DEREN': 'Debug error response enable: 1 = debugger accesses that violate the DTGU get an error response.',
    'MEMSYSCTL.DTGU_CFG.BLKSZ': 'Block size: 2^(BLKSZ+5) bytes per look-up-table bit.',
    'MEMSYSCTL.DTGU_CFG.NUMBLKS': 'Number of blocks: 2^NUMBLKS.',
    'MEMSYSCTL.DTGU_CFG.PRESENT': 'DTGU present.',
    # ── PWRMODCTL ────────────────────────────────────────────────────────────
    'PWRMODCTL.CPDLPSTATE.CLPSTATE': 'Core low-power state requested on deep sleep: 0 = ON, 1 = ON with the clock stopped, 2 = retention, 3 = OFF.',
    'PWRMODCTL.CPDLPSTATE.ELPSTATE': 'EPU (FPU/MVE) low-power state: 0 = ON, 2 = retention, 3 = OFF.',
    'PWRMODCTL.CPDLPSTATE.RLPSTATE': 'RAM (caches/TCM) low-power state: 0 = ON, 2 = retention, 3 = OFF.',
    'PWRMODCTL.DPDLPSTATE.DLPSTATE': 'Debug power domain low-power state: 0 = ON, 2 = retention, 3 = OFF.',
    # ── EWIC ─────────────────────────────────────────────────────────────────
    'EWIC.EWIC_CR.EN': 'EWIC enable. Set before powering down so wake-up events are latched.',
    'EWIC.EWIC_ASCR.ASPD': 'Automatic sequence on power-down: 1 = the EWIC copies the NVIC enables into its masks automatically when the processor powers down.',
    'EWIC.EWIC_ASCR.ASPU': 'Automatic sequence on power-up: 1 = latched events are transferred to the NVIC automatically on power-up.',
    'EWIC.EWIC_NUMID.NUMEVENT': 'Number of events supported.',
    'EWIC.EWIC_MASKA.EVENT': 'Wake on the EVENT (RXEV) input.',
    'EWIC.EWIC_MASKA.NMI': 'Wake on NMI.',
    'EWIC.EWIC_MASKA.EDBGREQ': 'Wake on an external debug request.',
    'EWIC.EWIC_MASK.IRQ': 'Bit k = 1: wake on IRQ 32(n−1)+k.',
    'EWIC.EWIC_PENDA.EVENT': 'EVENT input was latched.',
    'EWIC.EWIC_PENDA.NMI': 'NMI was latched.',
    'EWIC.EWIC_PENDA.EDBGREQ': 'External debug request was latched.',
    'EWIC.EWIC_PEND.IRQ': 'Bit k = 1: IRQ 32(n−1)+k was latched.',
    'EWIC.EWIC_PSR.NZA': 'EWIC_PENDA is non-zero.',
    'EWIC.EWIC_PSR.NZ': 'Bit n−1 = 1: EWIC_PENDn is non-zero.',
    'EWIC_ISA.EVENTSPR.EVENT': 'Write 1 to latch an EVENT.',
    'EWIC_ISA.EVENTSPR.NMI': 'Write 1 to latch an NMI.',
    'EWIC_ISA.EVENTSPR.EDBGREQ': 'Write 1 to latch an external debug request.',
    'EWIC_ISA.EVENTMASKA.EVENT': 'Wake on EVENT is enabled.',
    'EWIC_ISA.EVENTMASKA.NMI': 'Wake on NMI is enabled.',
    'EWIC_ISA.EVENTMASKA.EDBGREQ': 'Wake on external debug request is enabled.',
    'EWIC_ISA.EVENTMASK.IRQ': 'Bit k = 1: wake on IRQ 32(n−1)+k is enabled.',
    # ── STL ──────────────────────────────────────────────────────────────────
    'STL.STLNVICPENDOR.INTNUM': 'Interrupt number of the highest-priority pending interrupt.',
    'STL.STLNVICPENDOR.PRIORITY': 'Its priority.',
    'STL.STLNVICPENDOR.TARGET': 'Its target security state: 0 = Secure, 1 = Non-secure.',
    'STL.STLNVICPENDOR.VALID': '1 = an interrupt is pending (the other fields are valid).',
    'STL.STLNVICACTVOR.INTNUM': 'Interrupt number of the highest-priority active interrupt.',
    'STL.STLNVICACTVOR.PRIORITY': 'Its priority.',
    'STL.STLNVICACTVOR.TARGET': 'Its target security state: 0 = Secure, 1 = Non-secure.',
    'STL.STLNVICACTVOR.VALID': '1 = an interrupt is active (the other fields are valid).',
    'STL.STLIDMPUSR.DATA': 'Perform a data-side MPU lookup.',
    'STL.STLIDMPUSR.INSTR': 'Perform an instruction-side MPU lookup.',
    'STL.STLIDMPUSR.ADDR': 'Address to look up, bits [31:5].',
    'STL.STLIMPUOR.ATTR': 'Attributes returned by the instruction-side lookup.',
    'STL.STLIMPUOR.HITREGION': 'Region number that matched (instruction side).',
    'STL.STLD0MPUOR.ATTR': 'Attributes returned by the data-side lookup.',
    'STL.STLD0MPUOR.HITREGION': 'Region number that matched (data side).',
    'STL.STLD1MPUOR.ATTR': 'Attributes returned by the data-side lookup.',
    'STL.STLD1MPUOR.HITREGION': 'Region number that matched (data side).',
    'STL.STLD2MPUOR.ATTR': 'Attributes returned by the data-side lookup.',
    'STL.STLD2MPUOR.HITREGION': 'Region number that matched (data side).',
    'STL.STLD3MPUOR.ATTR': 'Attributes returned by the data-side lookup.',
    'STL.STLD3MPUOR.HITREGION': 'Region number that matched (data side).',
    'STL.STLDMPUOR.ATTR': 'Attributes returned by the data-side lookup.',
    'STL.STLDMPUOR.HITREGION': 'Region number that matched (data side).',
    'STL.STLSTBSLOTSR.STBSLOTNUM': 'Store buffer slot selected.',
    'STL.STLSTBSLOTSR.VALID': 'Slot valid.',
    'STL.STLLFDENTRYSR.LFDENTRYNUM': 'Line-fill data entry selected.',
    'STL.STLLFDENTRYSR.VALID': 'Entry valid.',
    # ── EMSS (STAR-MC1) ──────────────────────────────────────────────────────
    'EMSS.CACR.FORCEWT': 'Force write-through: 1 = all cacheable data is cached write-through.',
    'EMSS.CACR.DCACTIVE': 'Data cache active (read-only).',
    'EMSS.CACR.ICACTIVE': 'Instruction cache active (read-only).',
    'EMSS.CACR.DCCLEAN': 'Data cache clean (read-only): 1 = no dirty lines.',
    'EMSS.ITCMCR.EN': 'ITCM enable.',
    'EMSS.ITCMCR.SZ': _TCM_SZ,
    'EMSS.DTCMCR.EN': 'DTCM enable.',
    'EMSS.DTCMCR.SZ': _TCM_SZ,
}

PATTERN_FIELD_DESC = []
ENUMS = {}
RESET_VALUES = {}
REGISTER_ACCESS = {}
FIELD_ACCESS = {
    'MEMSYSCTL.MSCR.DCACTIVE': 'read-only', 'MEMSYSCTL.MSCR.ICACTIVE': 'read-only', 'MEMSYSCTL.MSCR.DCCLEAN': 'read-only',
    'SCB.ITCMCR.SZ': 'read-only', 'SCB.DTCMCR.SZ': 'read-only', 'SCB.AHBPCR.SZ': 'read-only',
    'MEMSYSCTL.ITCMCR.SZ': 'read-only', 'MEMSYSCTL.DTCMCR.SZ': 'read-only', 'MEMSYSCTL.PAHBCR.SZ': 'read-only',
}
FIELD_WIDTH_OVERRIDES = {}
DROP_FIELDS = set()
EXTRA_FIELDS = {
    'MEMSYSCTL.ITGU_LUT': [('LUT', 0, 32, 'Bit k: ITCM block 32n+k is Non-secure (1) or Secure (0).')],
    'MEMSYSCTL.DTGU_LUT': [('LUT', 0, 32, 'Bit k: DTCM block 32n+k is Non-secure (1) or Secure (0).')],
    'EWIC.EWIC_CLRMASK': [('CLRMASK', 0, 32, 'Write to clear all EWIC mask registers.')],
    'PRCCFGINF.CFGINFOSEL': [('SEL', 0, 32, 'Index of the configuration information word to read.')],
    'PRCCFGINF.CFGINFORD': [('DATA', 0, 32, 'Configuration information word.')],
}
