# Copyright 2026 Arm Limited
# Licensed under the Apache License, Version 2.0; see gen_core_svd.py.
"""System Control Space: SCB, SysTick, NVIC, ICB/SCnSCB, MPU, SAU, FPU, DCB, DIB.
Condensed from the ARMv6-M (DDI0419), ARMv7-M (DDI0403) and ARMv8-M (DDI0553) ARMs."""

PERIPHERAL_DESC = {
    'SCB': 'System Control Block: CPUID, exception control and state (ICSR, AIRCR, SHCSR), system configuration (SCR, CCR), '
           'system handler priorities, the fault status and address registers (CFSR, HFSR, DFSR, MMFAR, BFAR), CPU feature IDs, '
           'coprocessor access control, and on cores with caches the cache ID and maintenance registers.',
    'SysTick': '24-bit system timer that counts down from LOAD to 0 on the processor or reference clock and can raise the SysTick exception; '
               'the usual RTOS tick source. Banked per security state on ARMv8-M with the Security Extension.',
    'NVIC': 'Nested Vectored Interrupt Controller: enable, pending, active and priority registers for the external interrupts '
            '(IRQ0 = exception 16) and the software trigger register. Bit k of register n refers to IRQ 32n+k.',
    'SCnSCB': 'System control registers not in the SCB: the interrupt controller type and the implementation-defined Auxiliary Control Register.',
    'ICB': 'Implementation Control Block (ARMv8.1-M): interrupt controller type, the implementation-defined Auxiliary Control Register and coprocessor power control.',
    'MPU': 'Memory Protection Unit (optional): programmable regions with access permissions and memory attributes, checked on every access. '
           'ARMv6-M/v7-M (PMSAv7) use RBAR/RASR power-of-two regions; ARMv8-M (PMSAv8) uses RBAR/RLAR base-limit regions with MAIR attributes.',
    'SAU': 'Security Attribution Unit (ARMv8-M Security Extension): defines which address ranges are Non-secure or Secure Non-secure-callable; '
           'everything else is Secure. Also holds the SecureFault status and address registers.',
    'FPU': 'Floating-Point Unit control: context control (lazy stacking, automatic state preservation), the lazy-stacking frame address, '
           'the default FPSCR and the VFP/MVE feature registers. Enable the FPU through SCB.CPACR (CP10/CP11) before use.',
    'DCB': 'Debug Control Block: halting debug control and status (DHCSR), core register access from the debugger (DCRSR/DCRDR), '
           'vector catch, the DebugMonitor exception and trace enable (DEMCR), and on ARMv8-M debug authentication and security control.',
    'DIB': 'Debug Identification Block (ARMv8-M): software lock, debug authentication status and the SCS CoreSight architecture and type IDs.',
}

REGISTER_DESC = {
    'SysTick.CTRL': 'SysTick Control and Status Register: enable, interrupt enable, clock source and the sticky count-to-zero flag.',
    'SysTick.LOAD': 'SysTick Reload Value Register: value loaded into VAL when the counter reaches 0. A period of N clocks needs RELOAD = N−1.',
    'SysTick.VAL': 'SysTick Current Value Register: the current count. Any write clears it to 0 and clears CTRL.COUNTFLAG; the next reload comes from LOAD.',
    'SysTick.CALIB': 'SysTick Calibration Register: implementation-defined reload value for a 10 ms tick and whether a reference clock exists.',
    'NVIC.ISERn': 'Interrupt Set-Enable Register n (IRQ 32n..32n+31): write 1 to enable an interrupt, 0 has no effect; reads the enable state.',
    'NVIC.ICERn': 'Interrupt Clear-Enable Register n (IRQ 32n..32n+31): write 1 to disable an interrupt, 0 has no effect; reads the enable state.',
    'NVIC.ISPRn': 'Interrupt Set-Pending Register n (IRQ 32n..32n+31): write 1 to set an interrupt pending; reads the pending state.',
    'NVIC.ICPRn': 'Interrupt Clear-Pending Register n (IRQ 32n..32n+31): write 1 to clear a pending interrupt; reads the pending state.',
    'NVIC.IABRn': 'Interrupt Active Bit Register n (IRQ 32n..32n+31): 1 = the interrupt handler is active (executing or preempted). Read-only.',
    'NVIC.ITNSn': 'Interrupt Target Non-secure Register n (Security Extension): 1 = IRQ 32n+k targets Non-secure state. Secure access only; RAZ/WI from Non-secure.',
    'NVIC.IPRn': 'Interrupt Priority Register n: one byte per interrupt, IRQ 4n+0 in bits [7:0] up to IRQ 4n+3 in [31:24]. Lower value = higher priority; '
                 'only the top nvicPrioBits of each byte are implemented (ARMv6-M: 2, typical ARMv7-M: 3-4).',
    'NVIC.STIR': 'Software Trigger Interrupt Register: writing an interrupt number sets that interrupt pending (like ISPR). Unprivileged writes need CCR.USERSETMPEND.',
    'SCB.CPUID': 'CPUID Base Register: implementer, part number, architecture and revision of the processor (read-only).',
    'SCB.ICSR': 'Interrupt Control and State Register: active and pending exception numbers, and set/clear-pending controls for NMI, PendSV and SysTick.',
    'SCB.VTOR': 'Vector Table Offset Register: base address of the exception vector table. Must be aligned to the table size rounded up to a power of two '
                '(at least 128 bytes). Reset value is implementation defined (usually 0; set by SystemInit when the table is relocated).',
    'SCB.AIRCR': 'Application Interrupt and Reset Control Register: priority grouping, endianness, system reset request and (ARMv8-M) security '
                 'attribution of BusFault/HardFault/NMI. Writes must place 0x05FA in VECTKEY or are ignored.',
    'SCB.SCR': 'System Control Register: sleep-on-exit, deep sleep selection and send-event-on-pending.',
    'SCB.CCR': 'Configuration and Control Register: trapping of divide-by-zero and unaligned accesses, stack alignment, unprivileged STIR access, '
               'Thread-mode return rules, and on cached cores the instruction/data cache and branch predictor enables.',
    'SCB.SHCSR': 'System Handler Control and State Register: enable bits for the configurable fault exceptions and the active/pending state of every system handler. '
                 'A configurable fault whose enable bit is 0 escalates to HardFault.',
    'SCB.CFSR': 'Configurable Fault Status Register: MemManage (bits [7:0]), BusFault ([15:8]) and UsageFault ([31:16]) status. Bits are sticky and write-1-to-clear. '
                'With HFSR.FORCED set, this register holds the cause of the escalated HardFault.',
    'SCB.HFSR': 'HardFault Status Register: why a HardFault was taken — vector table read error, escalation of a configurable fault (see CFSR) or a debug event. Write 1 to clear.',
    'SCB.DFSR': 'Debug Fault Status Register: which debug event occurred (halt, breakpoint, watchpoint, vector catch, external request). Sticky, write 1 to clear.',
    'SCB.MMFAR': 'MemManage Fault Address Register: the data address that caused a MemManage fault, valid when CFSR.MMARVALID is set.',
    'SCB.BFAR': 'BusFault Address Register: the data address of a precise BusFault, valid when CFSR.BFARVALID is set. Not updated for imprecise faults.',
    'SCB.AFSR': 'Auxiliary Fault Status Register: implementation-defined fault status (Cortex-M7 reports AXI/TCM/AHBP errors here and in ABFSR). Write 1 to clear.',
    'SCB.SFSR': 'SecureFault Status Register (Security Extension): why a SecureFault was taken. Sticky, write 1 to clear. Secure access only.',
    'SCB.SFAR': 'SecureFault Address Register: the address that caused an AUVIOL SecureFault, valid when SFSR.SFARVALID is set.',
    'SCB.ID_PFRn': 'Processor Feature Register n: ID_PFR0 lists the supported instruction sets (Thumb, Thumb-2), ID_PFR1 the programmers model (M-profile, Security Extension). Read-only.',
    'SCB.ID_DFR': 'Debug Feature Register: the debug model implemented (M-profile debug, Unprivileged Debug Extension). Read-only.',
    'SCB.ID_AFR': 'Auxiliary Feature Register: implementation-defined features. Read-only.',
    'SCB.ID_MMFRn': 'Memory Model Feature Register n: PMSA support, cache and TCM features, alignment and barrier support. Read-only.',
    'SCB.ID_ISARn': 'Instruction Set Attribute Register n: which instruction classes are implemented (e.g. ID_ISAR5 for the SIMD/MVE and FP features on ARMv8.1-M). Read-only.',
    'SCB.CLIDR': 'Cache Level ID Register: which caches exist at each level and the levels of coherence and unification. Read-only.',
    'SCB.CTR': 'Cache Type Register: minimum instruction and data cache line sizes and the exclusives/write-back granules. Read-only.',
    'SCB.CCSIDR': 'Cache Size ID Register: line size, associativity, number of sets and write policies of the cache selected by CSSELR. Read-only.',
    'SCB.CSSELR': 'Cache Size Selection Register: selects which cache (level, instruction or data) CCSIDR describes.',
    'SCB.CPACR': 'Coprocessor Access Control Register: access rights for coprocessors 0-7 and for the FPU/MVE (CP10 and CP11, which must be set identically). '
                 'An FP instruction with CP10/CP11 = 0 raises a NOCP UsageFault — the classic "FPU not enabled" HardFault.',
    'SCB.NSACR': 'Non-secure Access Control Register (Security Extension): which coprocessors Non-secure software may use. Secure access only.',
    'SCB.STIR': 'Software Triggered Interrupt Register: writing an interrupt number sets it pending (alias of NVIC.STIR at 0xE000EF00).',
    'SCB.ICIALLU': 'Instruction Cache Invalidate All to PoU: write any value to invalidate the whole instruction cache (and branch predictor). Write-only.',
    'SCB.ICIMVAU': 'Instruction Cache Invalidate by address to PoU: write an address to invalidate the I-cache line containing it. Write-only.',
    'SCB.DCIMVAC': 'Data Cache Invalidate by address to PoC: write an address to invalidate (discard) the D-cache line containing it. Write-only.',
    'SCB.DCISW': 'Data Cache Invalidate by Set/Way: write a set and way (see fields) to invalidate that line. Write-only.',
    'SCB.DCCMVAU': 'Data Cache Clean by address to PoU: write an address to clean (write back) the line containing it to the point of unification. Write-only.',
    'SCB.DCCMVAC': 'Data Cache Clean by address to PoC: write an address to clean (write back) the line containing it to the point of coherency. Write-only.',
    'SCB.DCCSW': 'Data Cache Clean by Set/Way: write a set and way to clean that line. Write-only.',
    'SCB.DCCIMVAC': 'Data Cache Clean and Invalidate by address to PoC: write an address to write back and then invalidate its line. Write-only.',
    'SCB.DCCISW': 'Data Cache Clean and Invalidate by Set/Way. Write-only.',
    'SCB.BPIALL': 'Branch Predictor Invalidate All: write any value to invalidate all branch predictor state. Write-only.',
    'SCB.RFSR': 'RAS Fault Status Register (ARMv8.1-M RAS extension): records the most recent uncontained error. Write to clear.',
    'SCnSCB.ICTR': 'Interrupt Controller Type Register: how many interrupt lines the NVIC supports, in groups of 32. Read-only.',
    'ICB.ICTR': 'Interrupt Controller Type Register: how many interrupt lines the NVIC supports, in groups of 32. Read-only.',
    'SCnSCB.ACTLR': 'Auxiliary Control Register: implementation-defined controls that disable individual performance features (write buffering, instruction folding, '
                    'interruptible multi-cycle instructions, FPU behaviours). Usually left at reset; DISDEFWBUF is useful to make imprecise BusFaults precise while debugging.',
    'ICB.ACTLR': 'Auxiliary Control Register: implementation-defined controls that disable individual micro-architectural features of the core. Usually left at reset.',
    'SCnSCB.CPPWR': 'Coprocessor Power Control Register (ARMv8-M): per-coprocessor "state unknown" permissions that let the implementation power-gate the FPU/MVE and custom coprocessors.',
    'ICB.CPPWR': 'Coprocessor Power Control Register (ARMv8.1-M): per-coprocessor "state unknown" permissions that let the implementation power-gate the FPU/MVE and custom coprocessors.',
    'MPU.TYPE': 'MPU Type Register: how many regions the MPU implements (0 = no MPU). Read-only.',
    'MPU.CTRL': 'MPU Control Register: global enable, behaviour during HardFault/NMI, and the privileged default memory map.',
    'MPU.RNR': 'MPU Region Number Register: selects the region that RBAR and RASR/RLAR access.',
    'MPU.RBAR': 'MPU Region Base Address Register for the region selected by RNR (ARMv7-M: also selects the region when VALID is set). ARMv8-M: base address, shareability, access permissions and XN.',
    'MPU.RASR': 'MPU Region Attribute and Size Register (ARMv7-M/v6-M PMSAv7): enable, power-of-two size, subregion disables and the memory attributes/permissions of the selected region.',
    'MPU.RLAR': 'MPU Region Limit Address Register (ARMv8-M PMSAv8): inclusive end address, attribute index into MAIR0/1 and enable of the selected region.',
    'MPU.RBAR_A1': 'Alias of RBAR that accesses region RNR+1, so up to four regions can be programmed with a single STM. Same fields as RBAR.',
    'MPU.RBAR_A2': 'Alias of RBAR that accesses region RNR+2. Same fields as RBAR.',
    'MPU.RBAR_A3': 'Alias of RBAR that accesses region RNR+3. Same fields as RBAR.',
    'MPU.RASR_A1': 'Alias of RASR that accesses region RNR+1. Same fields as RASR.',
    'MPU.RASR_A2': 'Alias of RASR that accesses region RNR+2. Same fields as RASR.',
    'MPU.RASR_A3': 'Alias of RASR that accesses region RNR+3. Same fields as RASR.',
    'MPU.RLAR_A1': 'Alias of RLAR that accesses region RNR+1. Same fields as RLAR.',
    'MPU.RLAR_A2': 'Alias of RLAR that accesses region RNR+2. Same fields as RLAR.',
    'MPU.RLAR_A3': 'Alias of RLAR that accesses region RNR+3. Same fields as RLAR.',
    'MPU.MAIR0': 'MPU Memory Attribute Indirection Register 0: memory type/cacheability encodings 0-3 referenced by RLAR.AttrIndx.',
    'MPU.MAIR1': 'MPU Memory Attribute Indirection Register 1: memory type/cacheability encodings 4-7 referenced by RLAR.AttrIndx.',
    'SAU.CTRL': 'SAU Control Register: enable, and what the memory map looks like while the SAU is disabled.',
    'SAU.TYPE': 'SAU Type Register: number of SAU regions implemented (0, 4 or 8 on Arm cores). Read-only.',
    'SAU.RNR': 'SAU Region Number Register: selects the region that RBAR and RLAR access.',
    'SAU.RBAR': 'SAU Region Base Address Register: start address (32-byte aligned) of the selected region.',
    'SAU.RLAR': 'SAU Region Limit Address Register: inclusive end address, Non-secure-callable attribute and enable of the selected region.',
    'SAU.SFSR': 'SecureFault Status Register: why a SecureFault was taken. Sticky, write 1 to clear. Also visible at SCB offset 0xE4.',
    'SAU.SFAR': 'SecureFault Address Register: the address that caused an AUVIOL SecureFault, valid when SFSR.SFARVALID is set.',
    'FPU.FPCCR': 'Floating-Point Context Control Register: automatic and lazy FP state preservation on exception entry, and which exceptions may be taken while a lazy save is pending.',
    'FPU.FPCAR': 'Floating-Point Context Address Register: location of the unpopulated FP register space (S0-S15, FPSCR) in the exception stack frame while FPCCR.LSPACT is set.',
    'FPU.FPDSCR': 'Floating-Point Default Status Control Register: the FPSCR mode bits (rounding, flush-to-zero, default NaN, alternative half-precision) loaded on exception entry / when a new FP context starts.',
    'FPU.MVFR0': 'Media and VFP Feature Register 0: register bank size, single/double precision, divide, square root and rounding support. Read-only.',
    'FPU.MVFR1': 'Media and VFP Feature Register 1: flush-to-zero, default NaN, half-precision, fused MAC and (ARMv8.1-M) MVE support. Read-only.',
    'FPU.MVFR2': 'Media and VFP Feature Register 2: miscellaneous FPv5 features (VSEL, VCVT rounding variants, VRINT, VMAXNM/VMINNM). Read-only.',
    'DCB.DHCSR': 'Debug Halting Control and Status Register: debugger enable, halt, step and interrupt masking (writes need 0xA05F in bits [31:16], DBGKEY), and read-only '
                 'processor status (halted, sleeping, locked up, reset since last read) in the same upper bits.',
    'DCB.DCRSR': 'Debug Core Register Selector Register: with the processor halted, selects a core register to transfer to or from DCRDR. Poll DHCSR.S_REGRDY for completion.',
    'DCB.DCRDR': 'Debug Core Register Data Register: data for DCRSR transfers. Also usable as a general debugger-to-target mailbox.',
    'DCB.DEMCR': 'Debug Exception and Monitor Control Register: vector catch on reset and faults, DebugMonitor exception control, and TRCENA, the global enable for DWT, ITM, ETM and TPIU.',
    'DCB.DAUTHCTRL': 'Debug Authentication Control Register (ARMv8-M): lets Secure software override the external SPIDEN/SPNIDEN debug authentication inputs.',
    'DCB.DSCSR': 'Debug Security Control and Status Register (ARMv8-M): the current security state of the core and which banked register set the debugger sees.',
    'DCB.DSCEMCR': 'Debug Set/Clear Exception and Monitor Control Register (ARMv8.1-M): atomic set/clear access to the DEMCR MON_PEND and MON_REQ bits.',
    'DIB.DLAR': 'SCS Software Lock Access Register: write 0xC5ACCE55 to unlock software writes to the SCS debug registers when the software lock is implemented (DLSR.SLI).',
    'DIB.DLSR': 'SCS Software Lock Status Register: whether a software lock exists and whether it is currently locked.',
    'DIB.DAUTHSTATUS': 'Debug Authentication Status Register: which kinds of debug (invasive/non-invasive, Secure/Non-secure, unprivileged) are currently enabled.',
    'DIB.DDEVARCH': 'SCS Device Architecture Register: CoreSight ARCHID of the debug architecture (0x2A04 = ARMv8-M debug) and the architect (Arm, 0x23B).',
    'DIB.DDEVTYPE': 'SCS Device Type Register: CoreSight major/sub type of the SCS (0x00 = processor system control).',
}

FIELD_DESC = {
    # ── SysTick ──────────────────────────────────────────────────────────────
    'SysTick.CTRL.ENABLE': 'Counter enable: 1 = SysTick counts down from LOAD to 0 and reloads.',
    'SysTick.CTRL.TICKINT': '1 = counting down to 0 sets the SysTick exception pending; 0 = poll COUNTFLAG instead.',
    'SysTick.CTRL.CLKSOURCE': 'Clock source: 0 = external reference clock (implementation defined, e.g. HCLK/8), 1 = processor clock.',
    'SysTick.CTRL.COUNTFLAG': 'Reads 1 if the counter reached 0 since the last read of this register. Cleared by reading CTRL or writing VAL.',
    'SysTick.LOAD.RELOAD': 'Value loaded into VAL when the counter reaches 0. A period of N clocks needs RELOAD = N−1; 0 is legal but the counter then never fires.',
    'SysTick.VAL.CURRENT': 'Current counter value. Any write clears the field to 0 and clears CTRL.COUNTFLAG.',
    'SysTick.CALIB.TENMS': 'Reload value for a 10 ms period with the reference clock, or 0 if unknown. Implementation defined.',
    'SysTick.CALIB.SKEW': '1 = TENMS is not exact (a 10 ms tick cannot be produced exactly).',
    'SysTick.CALIB.NOREF': '1 = no separate reference clock: CLKSOURCE reads 1 and cannot be cleared.',
    # ── NVIC ─────────────────────────────────────────────────────────────────
    'NVIC.STIR.INTID': 'Interrupt number to set pending (0 = IRQ0, i.e. exception 16). Unprivileged writes are allowed when CCR.USERSETMPEND is 1.',
    # ── SCB.CPUID ────────────────────────────────────────────────────────────
    'SCB.CPUID.REVISION': 'Minor revision pM of the rNpM product revision.',
    'SCB.CPUID.PARTNO': 'Part number: 0xC20 Cortex-M0, 0xC60 Cortex-M0+, 0xC21 Cortex-M1, 0xC23 Cortex-M3, 0xC24 Cortex-M4, 0xC27 Cortex-M7, 0xD20 Cortex-M23, '
                        '0xD21 Cortex-M33, 0xD31 Cortex-M35P, 0xD22 Cortex-M55, 0xD23 Cortex-M85, 0xD24 Cortex-M52.',
    'SCB.CPUID.ARCHITECTURE': 'Architecture: 0xC = ARMv6-M, 0xF = ARMv7-M or ARMv8-M (use ID_PFR/ID_ISAR for the details).',
    'SCB.CPUID.VARIANT': 'Major revision rN of the rNpM product revision.',
    'SCB.CPUID.IMPLEMENTER': 'Implementer code: 0x41 = Arm.',
    # ── SCB.ICSR ─────────────────────────────────────────────────────────────
    'SCB.ICSR.VECTACTIVE': 'Exception number of the currently executing handler; 0 in Thread mode. 2 NMI, 3 HardFault, 4 MemManage, 5 BusFault, 6 UsageFault, 7 SecureFault, '
                           '11 SVCall, 12 DebugMonitor, 14 PendSV, 15 SysTick, 16+n IRQn.',
    'SCB.ICSR.RETTOBASE': '1 = the current handler is the only active exception (an exception return would go to Thread mode); 0 = another exception is preempted.',
    'SCB.ICSR.VECTPENDING': 'Exception number of the highest-priority pending enabled exception, 0 if none. Not affected by PRIMASK/FAULTMASK/BASEPRI.',
    'SCB.ICSR.ISRPENDING': '1 = an external interrupt (IRQ, not NMI or a fault) is pending.',
    'SCB.ICSR.ISRPREEMPT': '1 = a pending exception will be serviced when the processor leaves Debug state (debug use only).',
    'SCB.ICSR.STTNS': 'SysTick Targets Non-secure (Security Extension, single-SysTick implementations): 1 = the SysTick exception targets Non-secure state. Secure write only.',
    'SCB.ICSR.PENDSTCLR': 'Write 1 to clear a pending SysTick exception. Reads as 0.',
    'SCB.ICSR.PENDSTSET': 'Write 1 to set the SysTick exception pending; reads 1 while it is pending.',
    'SCB.ICSR.PENDSVCLR': 'Write 1 to clear a pending PendSV. Reads as 0.',
    'SCB.ICSR.PENDSVSET': 'Write 1 to set PendSV pending (the usual RTOS context-switch trigger); reads 1 while it is pending.',
    'SCB.ICSR.PENDNMICLR': 'Write 1 to clear a pending NMI (ARMv8-M; Secure or debugger access only). Reads as 0.',
    'SCB.ICSR.NMIPENDSET': 'Write 1 to set NMI pending; NMI is taken at once unless a higher active priority (another NMI, HardFault at −1 is lower) or Debug state prevents it. Reads 1 while pending.',
    'SCB.ICSR.PENDNMISET': 'Write 1 to set NMI pending; NMI is taken at once unless another NMI is active or the processor is halted. Reads 1 while pending. Secure or debugger access only when BFHFNMINS = 0.',
    # ── SCB.VTOR ─────────────────────────────────────────────────────────────
    'SCB.VTOR.TBLOFF': 'Vector table base address. The table must be aligned to its size rounded up to a power of two (at least 128 bytes; the low bits read as zero).',
    'SCB.VTOR.TBLBASE': 'Cortex-M3 r0/r1 only: 0 = the table is in the Code region, 1 = in the SRAM region.',
    # ── SCB.AIRCR ────────────────────────────────────────────────────────────
    'SCB.AIRCR.VECTRESET': 'ARMv7-M, debug use only: write 1 (with VECTKEY) to reset the processor core but not the debug logic. Use SYSRESETREQ for a real reset.',
    'SCB.AIRCR.VECTCLRACTIVE': 'Debug use only: write 1 (with VECTKEY) to clear all active-exception state. Only while halted; otherwise unpredictable.',
    'SCB.AIRCR.SYSRESETREQ': 'Write 1 (with VECTKEY = 0x05FA) to request a system reset (asserts SYSRESETREQ to the reset controller). Self-clearing; NVIC_SystemReset() uses this.',
    'SCB.AIRCR.SYSRESETREQS': 'System reset request Secure only (Security Extension): 1 = only Secure software or the debugger can set SYSRESETREQ.',
    'SCB.AIRCR.DIT': 'Data Independent Timing (ARMv8.1-M): 1 = the execution time of data-processing instructions does not depend on the data values.',
    'SCB.AIRCR.IESB': 'Implicit Error Synchronization Barrier (ARMv8.1-M RAS): 1 = an error synchronization barrier is inserted on every exception entry and return.',
    'SCB.AIRCR.PRIGROUP': 'Priority grouping: bits [7:PRIGROUP+1] of each 8-bit priority are the group (preemption) priority, bits [PRIGROUP:0] the subpriority. '
                          '0 = 7 group bits (default), 7 = no preemption between interrupts (all subpriority).',
    'SCB.AIRCR.BFHFNMINS': 'BusFault, HardFault and NMI Non-secure (Security Extension): 1 = these exceptions target Non-secure state and Secure faults escalate to the Non-secure HardFault. 0 = they target Secure state.',
    'SCB.AIRCR.PRIS': 'Prioritize Secure exceptions (Security Extension): 1 = Non-secure exception priorities are mapped to the lower half of the range, so any Secure exception can preempt them.',
    'SCB.AIRCR.ENDIANNESS': 'Data endianness: 0 = little-endian, 1 = big-endian (BE8). Read-only, sampled at reset.',
    'SCB.AIRCR.VECTKEY': 'Register key: writes must contain 0x05FA here or the whole write is ignored. Reads as 0xFA05 (VECTKEYSTAT).',
    # ── SCB.SCR ──────────────────────────────────────────────────────────────
    'SCB.SCR.SLEEPONEXIT': '1 = the processor sleeps (as after WFI) whenever it returns from an exception handler to Thread mode. Interrupt-driven designs run entirely from handlers this way.',
    'SCB.SCR.SLEEPDEEP': '1 = WFI, WFE and sleep-on-exit request deep sleep (SLEEPDEEP output; the implementation-defined low-power mode, often stopping clocks/PLL) instead of sleep.',
    'SCB.SCR.SLEEPDEEPS': 'Sleep Deep Secure only (Security Extension): 1 = SLEEPDEEP can only be written from Secure state.',
    'SCB.SCR.SEVONPEND': 'Send Event on Pending: 1 = an interrupt becoming pending (even a disabled one) wakes the processor from WFE, enabling the WFE-polling idle pattern.',
    # ── SCB.CCR ──────────────────────────────────────────────────────────────
    'SCB.CCR.NONBASETHRDENA': 'Non-base Thread enable: 1 = a handler may return to Thread mode with other exceptions still active (by writing an EXC_RETURN with IPSR = 0); 0 = that is an INVPC UsageFault.',
    'SCB.CCR.USERSETMPEND': '1 = unprivileged software may write STIR to set interrupts pending.',
    'SCB.CCR.UNALIGN_TRP': '1 = unaligned halfword/word loads and stores raise an UNALIGNED UsageFault. Multi-word accesses (LDM/STM/LDRD/STRD) always fault when unaligned. Always 1 on ARMv6-M.',
    'SCB.CCR.DIV_0_TRP': '1 = SDIV/UDIV by zero raises a DIVBYZERO UsageFault; 0 = the result is 0.',
    'SCB.CCR.BFHFNMIGN': 'Bus faults ignored at priority −1/−2: 1 = precise data BusFaults are ignored (the load returns 0, the store is dropped) in HardFault, NMI and FAULTMASK handlers. Used by probing code that must not lock up.',
    'SCB.CCR.STKALIGN': '1 = the exception stack frame is 8-byte aligned (the stacked xPSR bit 9 records the adjustment). Always 1 on ARMv8-M and ARMv6-M; on ARMv7-M reset value 1 since r2p0.',
    'SCB.CCR.STKOFHFNMIGN': 'Stack overflow ignored at priority −1/−2 (ARMv8-M): 1 = stack limit checks are disabled while executing at HardFault/NMI priority.',
    'SCB.CCR.DC': 'Data cache enable. Invalidate the cache before enabling (SCB_EnableDCache does this); clean before disabling.',
    'SCB.CCR.IC': 'Instruction cache enable. Invalidate before enabling (SCB_EnableICache).',
    'SCB.CCR.BP': 'Branch prediction enable. Reads as 1 (RAO) on Cortex-M7; on ARMv8-M cores it is implementation defined whether it is writable.',
    'SCB.CCR.LOB': 'Loop and branch info cache enable (ARMv8.1-M low-overhead-branch extension). Reset value 1 where implemented.',
    'SCB.CCR.TRD': 'Thread reentrancy disabled (ARMv8.1-M): 1 = an exception return to Thread mode while Thread mode is already active in the exception stack (re-entry) is faulted with INVPC; 0 = allowed.',
    # ── SCB.SHCSR ────────────────────────────────────────────────────────────
    'SCB.SHCSR.MEMFAULTACT': 'MemManage exception active. Software may write the active bits to fix up exception state, but must usually leave them alone.',
    'SCB.SHCSR.BUSFAULTACT': 'BusFault exception active.',
    'SCB.SHCSR.HARDFAULTACT': 'HardFault exception active (ARMv8-M).',
    'SCB.SHCSR.USGFAULTACT': 'UsageFault exception active.',
    'SCB.SHCSR.SECUREFAULTACT': 'SecureFault exception active (Security Extension).',
    'SCB.SHCSR.NMIACT': 'NMI exception active (ARMv8-M).',
    'SCB.SHCSR.SVCALLACT': 'SVCall exception active.',
    'SCB.SHCSR.MONITORACT': 'DebugMonitor exception active.',
    'SCB.SHCSR.PENDSVACT': 'PendSV exception active.',
    'SCB.SHCSR.SYSTICKACT': 'SysTick exception active.',
    'SCB.SHCSR.USGFAULTPENDED': 'UsageFault pending (a higher-priority exception is running).',
    'SCB.SHCSR.MEMFAULTPENDED': 'MemManage pending.',
    'SCB.SHCSR.BUSFAULTPENDED': 'BusFault pending.',
    'SCB.SHCSR.SVCALLPENDED': 'SVCall pending.',
    'SCB.SHCSR.MEMFAULTENA': 'MemManage exception enable: 0 = an MPU fault escalates to HardFault (HFSR.FORCED).',
    'SCB.SHCSR.BUSFAULTENA': 'BusFault exception enable: 0 = bus errors escalate to HardFault.',
    'SCB.SHCSR.USGFAULTENA': 'UsageFault exception enable: 0 = undefined instructions, invalid state, NOCP, divide-by-zero etc. escalate to HardFault.',
    'SCB.SHCSR.SECUREFAULTENA': 'SecureFault exception enable: 0 = security violations escalate to (Secure) HardFault.',
    'SCB.SHCSR.SECUREFAULTPENDED': 'SecureFault pending.',
    'SCB.SHCSR.HARDFAULTPENDED': 'HardFault pending (ARMv8-M).',
    # ── SCB.CFSR ─────────────────────────────────────────────────────────────
    'SCB.CFSR.IACCVIOL': 'MemManage: instruction fetch from an address the MPU forbids (XN region, no execute permission, or a privileged-only region in unprivileged mode). MMFAR is not written.',
    'SCB.CFSR.DACCVIOL': 'MemManage: data access to an address the MPU forbids. MMFAR holds the address when MMARVALID is set; the stacked PC is the faulting instruction.',
    'SCB.CFSR.MUNSTKERR': 'MemManage while unstacking on exception return — the stack pointer or an MPU region was changed during the handler.',
    'SCB.CFSR.MSTKERR': 'MemManage while stacking on exception entry — typically a stack overflow into a region the MPU forbids (e.g. a guard region below a thread stack).',
    'SCB.CFSR.MLSPERR': 'MemManage during lazy floating-point state preservation (the FP frame at FPCAR is in a forbidden region).',
    'SCB.CFSR.MMARVALID': 'MMFAR holds a valid fault address. Read MMFAR before clearing this bit.',
    'SCB.CFSR.IBUSERR': 'BusFault on an instruction prefetch — executing from unmapped or faulting memory (corrupted PC/LR, wrong VTOR, jump through a bad function pointer).',
    'SCB.CFSR.PRECISERR': 'Precise data BusFault: the stacked PC is the faulting load/store and BFAR holds the address (when BFARVALID).',
    'SCB.CFSR.IMPRECISERR': 'Imprecise data BusFault: a buffered write failed after the instruction retired, so the stacked PC is somewhere after the faulting store and BFAR is not valid. '
                            'Set ACTLR.DISDEFWBUF (Cortex-M3/M4) or add a DSB after suspect stores to make it precise.',
    'SCB.CFSR.UNSTKERR': 'BusFault while unstacking on exception return (stack pointer corrupted or pointing at unmapped memory).',
    'SCB.CFSR.STKERR': 'BusFault while stacking on exception entry — the stack pointer points at unmapped memory (stack overflow past the end of RAM, uninitialised SP).',
    'SCB.CFSR.LSPERR': 'BusFault during lazy floating-point state preservation.',
    'SCB.CFSR.BFARVALID': 'BFAR holds a valid fault address (precise faults only). Read BFAR before clearing this bit.',
    'SCB.CFSR.UNDEFINSTR': 'UsageFault: undefined instruction — an unknown opcode (corrupted code, wrong instruction set, an FP/DSP/MVE instruction the core lacks), or a coprocessor instruction on ARMv8-M without CDE.',
    'SCB.CFSR.INVSTATE': 'UsageFault: invalid EPSR state — almost always a branch to an address with bit 0 clear (Thumb bit not set), e.g. a null or corrupted function pointer, or a vector table entry without |1.',
    'SCB.CFSR.INVPC': 'UsageFault: invalid PC load on exception return — a corrupted EXC_RETURN in LR, or an exception return inconsistent with the active exception state.',
    'SCB.CFSR.NOCP': 'UsageFault: no coprocessor — an FPU/MVE or coprocessor instruction while the unit is disabled (SCB.CPACR CP10/CP11, NSACR, CPPWR) or absent. The usual cause of "HardFault at first float operation".',
    'SCB.CFSR.STKOF': 'UsageFault: stack overflow — a push crossed the MSPLIM/PSPLIM stack limit (ARMv8-M).',
    'SCB.CFSR.UNALIGNED': 'UsageFault: unaligned access with CCR.UNALIGN_TRP set, or an unaligned multi-word access (LDM/STM/LDRD/STRD, exclusive or MVE vector access) which always faults.',
    'SCB.CFSR.DIVBYZERO': 'UsageFault: SDIV or UDIV by zero with CCR.DIV_0_TRP set.',
    # ── SCB.HFSR ─────────────────────────────────────────────────────────────
    'SCB.HFSR.VECTTBL': 'A bus error occurred reading the vector table during exception entry — VTOR points at unmapped memory, or the table is missing/corrupted.',
    'SCB.HFSR.FORCED': 'Escalated fault: a MemManage, BusFault, UsageFault or SecureFault that was disabled (SHCSR) or of insufficient priority became a HardFault. CFSR/SFSR still hold the original cause.',
    'SCB.HFSR.DEBUGEVT': 'A debug event caused the HardFault — e.g. a BKPT instruction executed with no debugger attached and DEMCR.MON_EN clear, or a vector catch. See DFSR.',
    # ── SCB.DFSR ─────────────────────────────────────────────────────────────
    'SCB.DFSR.HALTED': 'Halt requested by the debugger (DHCSR.C_HALT or C_STEP), a DebugMonitor step, or a PMU/EDBGRQ halt.',
    'SCB.DFSR.BKPT': 'Breakpoint: a BKPT instruction was executed or an FPB comparator matched.',
    'SCB.DFSR.DWTTRAP': 'A DWT watchpoint (data or address comparator) matched.',
    'SCB.DFSR.VCATCH': 'A vector catch fired (one of the DEMCR.VC_* bits): the processor halted on entry to the matching exception.',
    'SCB.DFSR.EXTERNAL': 'External debug request (the EDBGRQ input, typically driven by the CTI).',
    'SCB.DFSR.PMU': 'PMU counter overflow caused a debug event (ARMv8.1-M, DHCSR.C_PMOV).',
    # ── SCB ID / cache / coprocessor ─────────────────────────────────────────
    'SCB.ID_DFR.MProfDbg': 'M-profile debug model: 0x1 = M-profile debug v1 (ARMv7-M/v8.0-M), 0x2 = v2 (ARMv8.1-M).',
    'SCB.ID_DFR.UDE': 'Unprivileged Debug Extension (ARMv8.1-M): 0x1 = implemented.',
    'SCB.CLIDR.CTYPE1': 'Cache type at level 1: 0 none, 1 instruction only, 2 data only, 3 separate instruction and data, 4 unified.',
    'SCB.CLIDR.IC': 'Level-1 instruction cache implemented (CTYPE1 bit 0).',
    'SCB.CLIDR.DC': 'Level-1 data cache implemented (CTYPE1 bit 1).',
    'SCB.CLIDR.LOC': 'Level of Coherence: the number of cache levels to clean/invalidate for coherence with the point of coherency (1 = L1 only).',
    'SCB.CLIDR.LOUU': 'Level of Unification Uniprocessor: the number of cache levels to clean for instruction/data unification (1 = L1 only).',
    'SCB.CTR.IMINLINE': 'Log2 of the number of words in the smallest instruction cache line (3 = 32 bytes on Cortex-M7/M55/M85).',
    'SCB.CTR.DMINLINE': 'Log2 of the number of words in the smallest data cache line (3 = 32 bytes).',
    'SCB.CTR.ERG': 'Exclusives Reservation Granule: log2 words of the reservation granule of LDREX/STREX (0 = unknown).',
    'SCB.CTR.CWG': 'Cache Writeback Granule: log2 words of the maximum size written back by a clean (0 = unknown).',
    'SCB.CTR.FORMAT': 'Register format: 0b100 = ARMv7 CTR format.',
    'SCB.CCSIDR.LINESIZE': 'Log2(words per cache line) − 2: 1 = 32-byte lines.',
    'SCB.CCSIDR.ASSOCIATIVITY': 'Associativity − 1 (number of ways − 1; Cortex-M7: 1 for the 2-way I-cache, 3 for the 4-way D-cache).',
    'SCB.CCSIDR.NUMSETS': 'Number of sets − 1. Cache size = (NUMSETS+1) × (ASSOCIATIVITY+1) × line size.',
    'SCB.CCSIDR.WA': 'Write-allocation supported.',
    'SCB.CCSIDR.RA': 'Read-allocation supported.',
    'SCB.CCSIDR.WB': 'Write-back supported.',
    'SCB.CCSIDR.WT': 'Write-through supported.',
    'SCB.CSSELR.IND': 'Instruction not data: 0 = data or unified cache, 1 = instruction cache is described by CCSIDR.',
    'SCB.CSSELR.LEVEL': 'Cache level − 1 (0 = level 1).',
    'SCB.NSACR.CPn': 'Non-secure access to coprocessors 0-7: bit n = 1 allows Non-secure software to use coprocessor n.',
    'SCB.NSACR.CP10': '1 = Non-secure software may use the FPU/MVE (CP10). Must equal CP11.',
    'SCB.NSACR.CP11': '1 = Non-secure software may use the FPU/MVE (CP11). Must equal CP10.',
    'SCB.STIR.INTID': 'Interrupt number to set pending (0 = IRQ0). Unprivileged writes are allowed when CCR.USERSETMPEND is 1.',
    'SCB.DCISW.SET': 'Set index of the cache line (number of sets from CCSIDR).',
    'SCB.DCISW.WAY': 'Way of the cache line (0-3 on the 4-way Cortex-M7 data cache).',
    'SCB.DCISW.LEVEL': 'Cache level − 1 (0 = L1).',
    'SCB.DCCSW.SET': 'Set index of the cache line.',
    'SCB.DCCSW.WAY': 'Way of the cache line.',
    'SCB.DCCSW.LEVEL': 'Cache level − 1 (0 = L1).',
    'SCB.DCCISW.SET': 'Set index of the cache line.',
    'SCB.DCCISW.WAY': 'Way of the cache line.',
    'SCB.DCCISW.LEVEL': 'Cache level − 1 (0 = L1).',
    'SCB.RFSR.UET': 'Uncontainable error type: 0 = UC uncontainable, 1 = UEU unrecoverable, 2 = UEO restartable, 3 = UER recoverable.',
    'SCB.RFSR.IS': 'Implementation-specific syndrome of the recorded error.',
    'SCB.RFSR.V': 'Valid: 1 = a RAS error has been recorded in this register.',
    # ── SCB.SFSR / SAU.SFSR ──────────────────────────────────────────────────
    'SAU.SFSR.INVEP': 'Invalid entry point: a Non-secure branch into Secure code that did not land on an SG instruction in a Non-secure-callable region.',
    'SAU.SFSR.INVIS': 'Invalid integrity signature: the Secure exception frame being unstacked has a wrong integrity signature (stack corruption or wrong stack).',
    'SAU.SFSR.INVER': 'Invalid exception return: the EXC_RETURN or the exception stack does not match the security state (e.g. a Non-secure return from a Secure handler).',
    'SAU.SFSR.AUVIOL': 'Attribution unit violation: a Non-secure access to an address the SAU/IDAU marks Secure. SFAR holds the address when SFARVALID is set.',
    'SAU.SFSR.INVTRAN': 'Invalid transition: a Secure-to-Non-secure branch not made with BXNS/BLXNS (for example calling a Non-secure function pointer directly, or a return to Non-secure code via a plain BX).',
    'SAU.SFSR.LSPERR': 'Error during lazy floating-point state preservation across security states.',
    'SAU.SFSR.SFARVALID': 'SFAR holds a valid address (AUVIOL faults).',
    'SAU.SFSR.LSERR': 'Lazy state error: a Secure FP/MVE context could not be saved or restored across the security transition.',
    # ── SCnSCB / ICB ─────────────────────────────────────────────────────────
    'SCnSCB.ICTR.INTLINESNUM': 'Number of interrupt lines in groups of 32: the NVIC supports up to 32 × (INTLINESNUM+1) interrupts (0 = 1-32, 1 = 33-64, …).',
    'ICB.ICTR.INTLINESNUM': 'Number of interrupt lines in groups of 32: the NVIC supports up to 32 × (INTLINESNUM+1) interrupts.',
    'SCnSCB.ACTLR.DISMCYCINT': '1 = multi-cycle instructions (LDM, STM, 64-bit loads/stores, MVE) are not interruptible — worst-case interrupt latency rises but becomes deterministic.',
    'SCnSCB.ACTLR.DISDEFWBUF': '1 = disable the write buffer for default memory map accesses: every BusFault becomes precise, so PRECISERR and BFAR point at the offending store. Costs performance; use while debugging imprecise faults.',
    'SCnSCB.ACTLR.DISFOLD': '1 = disable IT-block folding (Cortex-M3/M4) / instruction folding (Cortex-M7).',
    'SCnSCB.ACTLR.ITCMLAEN': 'Cortex-M1: enable the lower alias of the ITCM at 0x00000000 (the ITCM otherwise appears only at its upper alias).',
    'SCnSCB.ACTLR.ITCMUAEN': 'Cortex-M1: enable the upper alias of the ITCM at 0x10000000.',
    'SCnSCB.ACTLR.DISFPCA': '1 = disable the automatic update of CONTROL.FPCA by FP instructions (Cortex-M4/M3 with FPU). Debug use only.',
    'SCnSCB.ACTLR.DISOOFP': '1 = disable out-of-order completion of floating-point instructions relative to integer instructions (Cortex-M4).',
    'SCnSCB.ACTLR.FPEXCODIS': '1 = disable the FPU exception outputs (FPIXC, FPUFC, FPOFC, FPDZC, FPIDC, FPIOC); the cumulative FPSCR flags still update.',
    'SCnSCB.ACTLR.DISRAMODE': '1 = disable the dynamic read-allocate mode of the data cache (Cortex-M7 switches to write-allocate-only for streaming writes when set).',
    'SCnSCB.ACTLR.DISITMATBFLUSH': '1 = disable the ITM and DWT ATB flush handshake.',
    'SCnSCB.ACTLR.DISBTACREAD': '1 = disable reading the Branch Target Address Cache (static prediction only).',
    'SCnSCB.ACTLR.DISBTACALLOC': '1 = disable allocation into the Branch Target Address Cache.',
    'SCnSCB.ACTLR.DISCRITAXIRUR': '1 = disable critical-word-first AXI read-under-read.',
    'SCnSCB.ACTLR.DISDI': 'Disable dual issue: one bit per instruction class (Cortex-M7 TRM table) — set to force single issue of that class.',
    'SCnSCB.ACTLR.DISISSCH1': 'Disable issue channel 1 per instruction class (Cortex-M7): forces those instructions onto channel 0.',
    'SCnSCB.ACTLR.DISDYNADD': '1 = disable dynamic allocation of ADD/SUB instructions to the two issue channels (Cortex-M7 r1).',
    'ICB.ACTLR.DISFOLD': '1 = disable instruction folding.',
    'ICB.ACTLR.DISLOLEP': '1 = disable low-overhead-loop end prediction (the LE branch is predicted only from the LO loop cache).',
    'ICB.ACTLR.DISLO': '1 = disable the low-overhead-loop (LO) cache; loops fall back to ordinary branch handling.',
    'ICB.ACTLR.DISLOBR': '1 = disable low-overhead-loop branch prediction.',
    'ICB.ACTLR.DISOLAPS': 'Disable overlapping of scalar instructions with MVE (vector) instructions in the pipeline (Secure-controlled variant).',
    'ICB.ACTLR.DISOLAP': '1 = disable overlapping (beat-wise interleaving) of MVE vector instructions with following instructions.',
    'ICB.ACTLR.FPEXCODIS': '1 = disable the FPU exception outputs; the cumulative FPSCR flags still update.',
    'ICB.ACTLR.DISNWAMODE': '1 = disable no-write-allocate mode of the data cache (write misses then allocate).',
    'ICB.ACTLR.DISITMATBFLUSH': '1 = disable the ITM and DWT ATB flush handshake.',
    'ICB.ACTLR.EVENTBUSEN_S': '1 = enable the Secure event bus (PMU/DWT event export for Secure events).',
    'ICB.ACTLR.EVENTBUSEN': '1 = enable the event bus (exports PMU events on the EVENT interface).',
    'ICB.ACTLR.DISCRITAXIRUR': '1 = disable critical-word-first AXI read-under-read.',
    'ICB.ACTLR.DISDI': 'Disable dual issue for the instruction classes selected by these bits (see the core TRM).',
    'ICB.ACTLR.DISCRITAXIRUW': '1 = disable critical-word-first AXI read-under-write.',
    'SCnSCB.CPPWR.SU10': 'State Unknown for CP10 (FPU/MVE): 1 = the implementation may power down the unit and its register state may become unknown; software must then re-initialise it.',
    'SCnSCB.CPPWR.SUS10': 'SU10 Secure only: 1 = SU10 can only be changed from Secure state.',
    'SCnSCB.CPPWR.SU11': 'State Unknown for CP11 (FPU/MVE), must equal SU10.',
    'SCnSCB.CPPWR.SUS11': 'SU11 Secure only.',
    'ICB.CPPWR.SU10': 'State Unknown for CP10 (FPU/MVE): 1 = the implementation may power down the unit and its register state may become unknown; software must then re-initialise it.',
    'ICB.CPPWR.SUS10': 'SU10 Secure only: 1 = SU10 can only be changed from Secure state.',
    'ICB.CPPWR.SU11': 'State Unknown for CP11 (FPU/MVE), must equal SU10.',
    'ICB.CPPWR.SUS11': 'SU11 Secure only.',
    # ── MPU ──────────────────────────────────────────────────────────────────
    'MPU.TYPE.SEPARATE': '0 = unified MPU (instruction and data share the regions). Always 0 on Cortex-M.',
    'MPU.TYPE.DREGION': 'Number of MPU regions implemented (0 = no MPU; Cortex-M cores offer 8 or 16).',
    'MPU.TYPE.IREGION': 'Number of instruction regions; always 0 (unified).',
    'MPU.CTRL.ENABLE': 'MPU enable. When 0 the default memory map applies to all accesses.',
    'MPU.CTRL.HFNMIENA': '1 = the MPU stays enabled during HardFault, NMI and FAULTMASK handlers; 0 = those handlers use the default memory map (the usual choice).',
    'MPU.CTRL.PRIVDEFENA': '1 = privileged accesses to addresses not covered by any enabled region use the default memory map; 0 = they raise a MemManage fault (unprivileged accesses always fault).',
    'MPU.RNR.REGION': 'Region number selected for RBAR/RASR (RLAR) accesses.',
    'MPU.RBAR.ADDR': 'Region base address. Must be aligned to the region size; the bits below the size (as set in RASR.SIZE) are ignored.',
    'MPU.RBAR.VALID': 'Write 1 to also write REGION into RNR in the same access, so base and number can be set with one store. Reads as 0.',
    'MPU.RBAR.REGION': 'Region number to select when VALID = 1; reads back the current RNR.',
    'MPU.RBAR.XN': 'Execute never: 1 = instruction fetches from this region fault.',
    'MPU.RBAR.AP': 'Access permissions: 0 = read/write privileged only, 1 = read/write any privilege, 2 = read-only privileged only, 3 = read-only any privilege.',
    'MPU.RBAR.SH': 'Shareability of Normal memory: 0 = non-shareable, 2 = outer shareable, 3 = inner shareable (1 reserved). Ignored for Device memory.',
    'MPU.RBAR.BASE': 'Region start address bits [31:5] (32-byte granularity).',
    'MPU.RASR.ENABLE': 'Region enable.',
    'MPU.RASR.SIZE': 'Region size = 2^(SIZE+1) bytes: 4 = 32 B (minimum), 7 = 256 B, 11 = 4 KB, 19 = 1 MB, 31 = 4 GB.',
    'MPU.RASR.SRD': 'Subregion disable: bit k = 1 disables the k-th eighth of the region (regions of 256 bytes or more). Lets a region punch holes in a larger one.',
    'MPU.RASR.B': 'Bufferable (with C and TEX selects the memory type: TEX=0 C=0 B=0 Strongly-ordered, B=1 Device; C=1 B=0 write-through, C=1 B=1 write-back).',
    'MPU.RASR.C': 'Cacheable (see B).',
    'MPU.RASR.S': 'Shareable: 1 = the region is shared with other bus masters (DMA) — cacheable shared memory is treated as non-cacheable on Cortex-M7 unless CACR.SIWT is set.',
    'MPU.RASR.TEX': 'Type extension: 0 = standard types via C/B, 1 with C=B=0 Normal non-cacheable, 1 with C=B=1 write-back write-allocate, 2 = Device non-shareable, 4-7 = separate outer/inner cache policies in TEX[1:0] and C/B.',
    'MPU.RASR.AP': 'Access permissions (privileged/unprivileged): 0 = no access, 1 = RW/no access, 2 = RW/RO, 3 = RW/RW, 5 = RO/no access, 6 or 7 = RO/RO.',
    'MPU.RASR.XN': 'Execute never: 1 = instruction fetches from this region raise an IACCVIOL MemManage fault.',
    'MPU.RLAR.EN': 'Region enable.',
    'MPU.RLAR.AttrIndx': 'Index (0-7) of the MAIR0/MAIR1 attribute byte that gives the memory type and cacheability of this region.',
    'MPU.RLAR.PXN': 'Privileged execute never (ARMv8.1-M): 1 = privileged instruction fetches from this region fault.',
    'MPU.RLAR.LIMIT': 'Region end address bits [31:5]; the low five bits are treated as 1, so the region is inclusive up to LIMIT + 31.',
    # ── SAU ──────────────────────────────────────────────────────────────────
    'SAU.CTRL.ENABLE': 'SAU enable. When 0 the whole address space is Secure (ALLNS = 0) or Non-secure (ALLNS = 1), subject to the IDAU.',
    'SAU.CTRL.ALLNS': 'All Non-secure: with the SAU disabled, 1 = memory not marked Secure by the IDAU is Non-secure, 0 = all memory is Secure.',
    'SAU.TYPE.SREGION': 'Number of SAU regions implemented (0, 4 or 8).',
    'SAU.RNR.REGION': 'Region selected for RBAR/RLAR accesses.',
    'SAU.RBAR.BADDR': 'Region start address bits [31:5] (32-byte granularity).',
    'SAU.RLAR.ENABLE': 'Region enable.',
    'SAU.RLAR.NSC': '1 = the region is Secure and Non-secure-callable (holds the SG entry veneers); 0 = the region is Non-secure.',
    'SAU.RLAR.LADDR': 'Region end address bits [31:5]; the low five bits are treated as 1 (inclusive limit).',
    # ── FPU ──────────────────────────────────────────────────────────────────
    'FPU.FPCCR.LSPACT': 'Lazy state preservation active: an FP context frame is reserved at FPCAR but the registers have not been saved yet. The first FP instruction in the handler triggers the save.',
    'FPU.FPCCR.USER': 'The reserved FP frame belongs to unprivileged (user) code.',
    'FPU.FPCCR.S': 'The reserved FP frame belongs to Secure code (Security Extension).',
    'FPU.FPCCR.THREAD': 'The reserved FP frame was allocated in Thread mode.',
    'FPU.FPCCR.HFRDY': 'HardFault ready: 1 = the priority when the frame was reserved allows HardFault to be taken during the lazy save.',
    'FPU.FPCCR.MMRDY': 'MemManage ready: 1 = MemManage can be taken during the lazy save (it was enabled and of sufficient priority).',
    'FPU.FPCCR.BFRDY': 'BusFault ready: 1 = BusFault can be taken during the lazy save.',
    'FPU.FPCCR.SFRDY': 'SecureFault ready: 1 = SecureFault can be taken during the lazy save.',
    'FPU.FPCCR.MONRDY': 'DebugMonitor ready: 1 = the monitor exception can be taken during the lazy save.',
    'FPU.FPCCR.SPLIMVIOL': 'Stack pointer limit violation: reserving the FP frame crossed the stack limit (ARMv8-M); the frame was not allocated.',
    'FPU.FPCCR.UFRDY': 'UsageFault ready: 1 = UsageFault can be taken during the lazy save.',
    'FPU.FPCCR.TS': 'Treat as Secure: 1 = all FP registers are treated as Secure — all 32 are stacked (and cleared) on Secure-to-Non-secure exception transitions. Secure access only.',
    'FPU.FPCCR.CLRONRETS': 'CLRONRET Secure only: 1 = CLRONRET can only be written from Secure state.',
    'FPU.FPCCR.CLRONRET': 'Clear on return: 1 = the caller-saved FP registers (S0-S15, FPSCR) are cleared on exception return from Secure to Non-secure state.',
    'FPU.FPCCR.LSPENS': 'LSPEN Secure only: 1 = LSPEN can only be written from Secure state.',
    'FPU.FPCCR.LSPEN': 'Lazy state preservation enable: 1 = on exception entry only space is reserved for S0-S15/FPSCR and the registers are saved only if the handler uses the FPU (default, saves ~17 cycles); 0 = always saved.',
    'FPU.FPCCR.ASPEN': 'Automatic state preservation enable: 1 = executing an FP instruction sets CONTROL.FPCA, so the next exception entry uses the extended (FP) stack frame. Default 1.',
    'FPU.FPCAR.ADDRESS': 'Address of the unpopulated S0-S15/FPSCR area in the exception stack frame (8-byte aligned), valid while FPCCR.LSPACT is 1.',
    'FPU.FPDSCR.LTPSIZE': 'Default loop tail-predication size for MVE (ARMv8.1-M); must be 4 (no tail predication) in this register.',
    'FPU.FPDSCR.FZ16': 'Default flush-to-zero mode for half-precision (ARMv8.1-M).',
    'FPU.FPDSCR.RMode': 'Default rounding mode: 0 = round to nearest, 1 = towards +∞, 2 = towards −∞, 3 = towards zero.',
    'FPU.FPDSCR.FZ': 'Default flush-to-zero mode: 1 = denormals are flushed to zero (not IEEE compliant, faster on some cores).',
    'FPU.FPDSCR.DN': 'Default NaN mode: 1 = any NaN result is the default NaN rather than propagating the input NaN.',
    'FPU.FPDSCR.AHP': 'Alternative half-precision: 1 = use the Arm alternative half-precision format (no infinities/NaNs) for conversions.',
    'FPU.MVFR0.SIMDReg': 'Register bank: 0x1 = 16 double-precision (S0-S31) registers, 0x2 = 32 double-precision registers.',
    'FPU.MVFR0.FPSP': 'Single-precision support: 0 = none, 2 = supported (VFPv3/FPv4/FPv5 level).',
    'FPU.MVFR0.FPDP': 'Double-precision support: 0 = none, 2 = supported (Cortex-M7 with the DP option, Cortex-M55/M85).',
    'FPU.MVFR0.FPExceptrap': 'Floating-point exception trapping: 0 = not supported (Cortex-M FPUs never trap; the cumulative FPSCR flags are set).',
    'FPU.MVFR0.FPDivide': 'VDIV supported: 1 = yes.',
    'FPU.MVFR0.FPSqrt': 'VSQRT supported: 1 = yes.',
    'FPU.MVFR0.FPShortvec': 'Short vector mode: 0 = not supported.',
    'FPU.MVFR0.FPRound': 'Rounding modes: 1 = all IEEE 754 rounding modes supported.',
    'FPU.MVFR1.FPFtZ': 'Flush-to-zero mode: 1 = supported (FPSCR.FZ).',
    'FPU.MVFR1.FPDNaN': 'Default NaN mode: 1 = supported (FPSCR.DN).',
    'FPU.MVFR1.MVE': 'M-profile Vector Extension (Helium): 0 = none, 1 = integer MVE, 2 = integer and floating-point MVE.',
    'FPU.MVFR1.FP16': 'Half-precision floating-point arithmetic (ARMv8.1-M): 1 = supported.',
    'FPU.MVFR1.FPHP': 'Half-precision conversions: 1 = single↔half, 2 = also double↔half, 3 = full half-precision arithmetic.',
    'FPU.MVFR1.FMAC': 'Fused multiply-accumulate (VFMA/VFMS/VFNMA/VFNMS): 1 = supported.',
    'FPU.MVFR2.FPMisc': 'Miscellaneous FPv5 features: 0x4 = VSEL, VCVTA/N/P/M, VRINT*, VMAXNM/VMINNM supported.',
    # ── DCB ──────────────────────────────────────────────────────────────────
    'DCB.DHCSR.C_DEBUGEN': 'Halting debug enable. Set by the debugger; cannot be set by software. While 0 the other C_* bits are ignored and BKPT with no monitor escalates to HardFault.',
    'DCB.DHCSR.C_HALT': 'Halt request: 1 = halt the processor (Debug state); 0 = run. Needs C_DEBUGEN = 1.',
    'DCB.DHCSR.C_STEP': 'Single step: 1 = when leaving Debug state, execute one instruction and halt again.',
    'DCB.DHCSR.C_MASKINTS': 'Mask PendSV, SysTick and IRQ (not NMI/faults) while stepping, so a step does not enter an interrupt handler. Change only while halted, together with C_HALT.',
    'DCB.DHCSR.C_SNAPSTALL': '1 = force the processor out of a stalled load/store (bus never responded). The instruction is abandoned, not restarted — the state afterwards is unpredictable; a reset is usually needed.',
    'DCB.DHCSR.C_PMOV': 'Halt on PMU overflow (ARMv8.1-M): 1 = a PMU counter overflow generates a halt debug event (DFSR.PMU).',
    'DCB.DHCSR.S_REGRDY': 'Register transfer complete: a DCRSR read/write has finished and DCRDR is valid. Read-only.',
    'DCB.DHCSR.S_HALT': 'Processor is in Debug state (halted). Read-only.',
    'DCB.DHCSR.S_SLEEP': 'Processor is sleeping (WFI, WFE or sleep-on-exit). Read-only.',
    'DCB.DHCSR.S_LOCKUP': 'Processor is in lockup state — a fault occurred at priority −1 or in NMI/HardFault with no way to escalate; PC reads 0xFFFFFFFE. Read-only.',
    'DCB.DHCSR.S_SDE': 'Secure debug enabled: 1 = halting debug is permitted in Secure state (DAUTHSTATUS.SID). Read-only.',
    'DCB.DHCSR.S_NSUIDE': 'Non-secure unprivileged invasive debug enabled (ARMv8.1-M UDE). Read-only.',
    'DCB.DHCSR.S_SUIDE': 'Secure unprivileged invasive debug enabled (ARMv8.1-M UDE). Read-only.',
    'DCB.DHCSR.S_FPD': 'Floating-point debuggable: 0 = the FP/MVE registers are not accessible to the debugger (unit powered down or Secure-only). Read-only (ARMv8.1-M).',
    'DCB.DHCSR.S_RETIRE_ST': 'Sticky: at least one instruction retired since the last read of DHCSR. Cleared on read.',
    'DCB.DHCSR.S_RESET_ST': 'Sticky: the processor was reset since the last read of DHCSR. Cleared on read.',
    'DCB.DHCSR.S_RESTART_ST': 'Sticky: the processor left Debug state (restarted) since the last read (ARMv8-M). Cleared on read.',
    'DCB.DCRSR.REGSEL': 'Register to transfer: 0-12 R0-R12, 13 SP (current), 14 LR, 15 DebugReturnAddress (PC), 16 xPSR, 17 MSP, 18 PSP, 20 packed CONTROL[31:24] FAULTMASK[16] BASEPRI[8] PRIMASK[0], '
                        '33 FPSCR, 64-95 S0-S31; ARMv8-M: 24 MSP_NS, 25 PSP_NS, 26 MSP_S, 27 PSP_S, 28 MSPLIM_S, 29 PSPLIM_S, 30 MSPLIM_NS, 31 PSPLIM_NS, 34/35 packed CONTROL/masks _S/_NS.',
    'DCB.DCRSR.REGWnR': 'Direction: 0 = read the selected register into DCRDR, 1 = write DCRDR to the selected register.',
    'DCB.DCRDR.DBGTMP': 'Data read from, or to be written to, the register selected by DCRSR.',
    'DCB.DEMCR.VC_CORERESET': 'Vector catch on core reset: halt immediately after reset (the "reset catch" debuggers use to stop at the first instruction). Needs C_DEBUGEN.',
    'DCB.DEMCR.VC_MMERR': 'Vector catch on MemManage fault entry.',
    'DCB.DEMCR.VC_NOCPERR': 'Vector catch on a NOCP (no coprocessor) UsageFault.',
    'DCB.DEMCR.VC_CHKERR': 'Vector catch on a checking-error UsageFault (UNALIGNED, DIVBYZERO).',
    'DCB.DEMCR.VC_STATERR': 'Vector catch on a state-error UsageFault (UNDEFINSTR, INVSTATE, INVPC).',
    'DCB.DEMCR.VC_BUSERR': 'Vector catch on BusFault entry.',
    'DCB.DEMCR.VC_INTERR': 'Vector catch on a fault during exception entry or return (stacking/unstacking errors, INVPC on return).',
    'DCB.DEMCR.VC_HARDERR': 'Vector catch on HardFault entry — with this set the core halts at the fault instead of running the HardFault handler.',
    'DCB.DEMCR.VC_SFERR': 'Vector catch on SecureFault entry (Security Extension).',
    'DCB.DEMCR.MON_EN': 'DebugMonitor exception enable: with no halting debugger attached, BKPT, FPB and DWT events raise the DebugMonitor exception (12) instead of a HardFault.',
    'DCB.DEMCR.MON_PEND': 'Set the DebugMonitor exception pending (software or debugger can use it to enter the monitor).',
    'DCB.DEMCR.MON_STEP': 'Monitor step: 1 = after the monitor returns, execute one instruction and re-enter the monitor (software single-step).',
    'DCB.DEMCR.MON_REQ': 'Monitor request semaphore: set by software to tell the monitor handler it was entered by request rather than by a debug event (not affected by hardware).',
    'DCB.DEMCR.SDME': 'Secure DebugMonitor enable: 1 = the DebugMonitor exception targets Secure state. Read-only status derived from the debug authentication signals.',
    'DCB.DEMCR.UMON_EN': 'Unprivileged monitor enable (ARMv8.1-M UDE): 1 = the DebugMonitor may be used for unprivileged debug.',
    'DCB.DEMCR.MONPRKEY': 'Monitor pending request key (ARMv8.1-M): a write to MON_PEND takes effect only if this bit is written as 1 in the same access.',
    'DCB.DEMCR.TRCENA': 'Trace enable: global enable for the DWT, ITM, ETM and TPIU. Must be 1 before any DWT/ITM register is written (CYCCNT, watchpoints, SWO output).',
    'DCB.DAUTHCTRL.SPIDENSEL': '1 = INTSPIDEN overrides the external SPIDEN input (Secure invasive debug enable).',
    'DCB.DAUTHCTRL.INTSPIDEN': 'Internal Secure invasive debug enable, used when SPIDENSEL = 1.',
    'DCB.DAUTHCTRL.SPNIDENSEL': '1 = INTSPNIDEN overrides the external SPNIDEN input (Secure non-invasive debug/trace enable).',
    'DCB.DAUTHCTRL.INTSPNIDEN': 'Internal Secure non-invasive debug enable, used when SPNIDENSEL = 1.',
    'DCB.DAUTHCTRL.FSDMA': 'Force Secure DebugMonitor allowed (ARMv8.1-M): 1 = the DebugMonitor is permitted in Secure state regardless of SPIDEN.',
    'DCB.DAUTHCTRL.UIDAPEN': 'Unprivileged invasive debug of the DAP enable (ARMv8.1-M UDE).',
    'DCB.DAUTHCTRL.UIDEN': 'Unprivileged invasive debug enable (ARMv8.1-M UDE): 1 = halting debug is allowed only in unprivileged code.',
    'DCB.DSCSR.SBRSELEN': 'Secure banked register select enable: 1 = SBRSEL chooses which security state\'s banked registers DCRSR accesses; 0 = the current state\'s.',
    'DCB.DSCSR.SBRSEL': 'Security state of the banked registers accessed through DCRSR when SBRSELEN = 1: 0 = Non-secure, 1 = Secure.',
    'DCB.DSCSR.CDS': 'Current domain Secure: 1 = the processor is in Secure state. The debugger may write it (with CDSKEY = 0) while halted to switch state.',
    'DCB.DSCSR.CDSKEY': 'CDS write key: CDS is only updated if this bit is written as 0 in the same access. Reads as 1.',
    'DCB.DSCEMCR.SET_MON_PEND': 'Write 1 to set DEMCR.MON_PEND.',
    'DCB.DSCEMCR.SET_MON_REQ': 'Write 1 to set DEMCR.MON_REQ.',
    'DCB.DSCEMCR.CLR_MON_PEND': 'Write 1 to clear DEMCR.MON_PEND.',
    'DCB.DSCEMCR.CLR_MON_REQ': 'Write 1 to clear DEMCR.MON_REQ.',
    # ── DIB ──────────────────────────────────────────────────────────────────
    'DIB.DLAR.KEY': 'Write 0xC5ACCE55 to unlock software access to the SCS debug registers; any other value locks them.',
    'DIB.DLSR.SLI': 'Software lock implemented.',
    'DIB.DLSR.SLK': 'Software lock status: 1 = locked (software writes to the debug registers are ignored; the debugger is never locked).',
    'DIB.DLSR.nTT': 'Not thirty-two bit: 0 = DLAR is a 32-bit register.',
    'DIB.DAUTHSTATUS.NSID': 'Non-secure invasive debug: 0 = not implemented, 2 = disabled, 3 = enabled.',
    'DIB.DAUTHSTATUS.NSNID': 'Non-secure non-invasive debug (trace): 0 = not implemented, 2 = disabled, 3 = enabled.',
    'DIB.DAUTHSTATUS.SID': 'Secure invasive debug: 0 = not implemented, 2 = disabled, 3 = enabled.',
    'DIB.DAUTHSTATUS.SNID': 'Secure non-invasive debug: 0 = not implemented, 2 = disabled, 3 = enabled.',
    'DIB.DAUTHSTATUS.NSUID': 'Non-secure unprivileged invasive debug (ARMv8.1-M UDE): 2 = disabled, 3 = enabled.',
    'DIB.DAUTHSTATUS.NSUNID': 'Non-secure unprivileged non-invasive debug: 2 = disabled, 3 = enabled.',
    'DIB.DAUTHSTATUS.SUID': 'Secure unprivileged invasive debug: 2 = disabled, 3 = enabled.',
    'DIB.DAUTHSTATUS.SUNID': 'Secure unprivileged non-invasive debug: 2 = disabled, 3 = enabled.',
    'DIB.DDEVARCH.ARCHPART': 'Architecture part: 0xA04 = M-profile system control space (with ARCHVER 2 → ARCHID 0x2A04, ARMv8-M debug).',
    'DIB.DDEVARCH.ARCHVER': 'Architecture version: 2 = ARMv8-M debug architecture.',
    'DIB.DDEVARCH.REVISION': 'Architecture revision.',
    'DIB.DDEVARCH.PRESENT': '1 = DDEVARCH is present and its contents are valid.',
    'DIB.DDEVARCH.ARCHITECT': 'JEP106 code of the architect: 0x23B = Arm.',
    'DIB.DDEVTYPE.MAJOR': 'Major type: 0 = miscellaneous / processor system control.',
    'DIB.DDEVTYPE.SUB': 'Sub type: 0 for the SCS.',
}

# SFSR/SFAR live in the SCB in the Arm ARM; the CMSIS header carries their bits under the SAU prefix.
FIELD_DESC.update({k.replace('SAU.SFSR.', 'SCB.SFSR.'): v for k, v in list(FIELD_DESC.items()) if k.startswith('SAU.SFSR.')})
FIELD_DESC.update({
    'SCB.DCISW.UC_SET': 'Set index when the Cortex-M52 cache is configured as a unified cache.',
    'SCB.DCISW.UC_WAY': 'Way when the Cortex-M52 cache is configured as a unified cache.',
    'SCB.DCCSW.UC_SET': 'Set index when the Cortex-M52 cache is configured as a unified cache.',
    'SCB.DCCSW.UC_WAY': 'Way when the Cortex-M52 cache is configured as a unified cache.',
    'SCB.DCCISW.UC_SET': 'Set index when the Cortex-M52 cache is configured as a unified cache.',
    'SCB.DCCISW.UC_WAY': 'Way when the Cortex-M52 cache is configured as a unified cache.',
})

# Text shared by any register whose field has this name (used only when no specific key exists).
COMMON_FIELD_DESC = {
    'ADDRESS': 'Address.',
}

import re as _re
PATTERN_FIELD_DESC = [
    (_re.compile(r'SCB\.NSACR\.CP(\d)'), '1 = Non-secure software may use coprocessor {0} (custom datapath extension / CDE coprocessor).'),
]

ENUMS = {
    'SysTick.CTRL.CLKSOURCE': [('External', 0, 'External reference clock (implementation defined)'), ('Processor', 1, 'Processor clock')],
    'SCB.AIRCR.ENDIANNESS': [('Little', 0, 'Little-endian data'), ('Big', 1, 'Big-endian (BE8) data')],
    'SCB.AIRCR.PRIGROUP': [(f'G{7 - n}S{n + 1}', n, f'{7 - n} group priority bits [7:{n + 1}], {n + 1} subpriority bits [{n}:0]') for n in range(8)],
    'MPU.RBAR.AP': [('RW_PRIV', 0, 'Read/write, privileged only'), ('RW_ANY', 1, 'Read/write, any privilege'),
                    ('RO_PRIV', 2, 'Read-only, privileged only'), ('RO_ANY', 3, 'Read-only, any privilege')],
    'MPU.RBAR.SH': [('NonShareable', 0, 'Non-shareable'), ('OuterShareable', 2, 'Outer shareable'), ('InnerShareable', 3, 'Inner shareable')],
    'MPU.RASR.AP': [('NoAccess', 0, 'No access'), ('PrivRW', 1, 'Privileged read/write, unprivileged no access'), ('PrivRW_UserRO', 2, 'Privileged read/write, unprivileged read-only'),
                    ('FullAccess', 3, 'Read/write for all'), ('PrivRO', 5, 'Privileged read-only, unprivileged no access'), ('ReadOnly', 6, 'Read-only for all'), ('ReadOnly_7', 7, 'Read-only for all')],
    'FPU.FPDSCR.RMode': [('RN', 0, 'Round to nearest'), ('RP', 1, 'Round towards plus infinity'), ('RM', 2, 'Round towards minus infinity'), ('RZ', 3, 'Round towards zero')],
}

RESET_VALUES = {
    'SCB.AIRCR': 0xFA050000,
    'SCB.CCR': 0x00000200,
    'FPU.FPCCR': 0xC0000000,
}

REGISTER_ACCESS = {
    'SCB.CPUID': 'read-only', 'SCB.STIR': 'write-only', 'NVIC.STIR': 'write-only', 'NVIC.IABRn': 'read-only',
}

FIELD_ACCESS = {
    'SysTick.CTRL.COUNTFLAG': 'read-only',
    'SCB.ICSR.VECTACTIVE': 'read-only', 'SCB.ICSR.RETTOBASE': 'read-only', 'SCB.ICSR.VECTPENDING': 'read-only',
    'SCB.ICSR.ISRPENDING': 'read-only', 'SCB.ICSR.ISRPREEMPT': 'read-only',
    'SCB.ICSR.PENDSTCLR': 'write-only', 'SCB.ICSR.PENDSVCLR': 'write-only', 'SCB.ICSR.PENDNMICLR': 'write-only',
    'SCB.AIRCR.ENDIANNESS': 'read-only',
    'DCB.DHCSR.S_REGRDY': 'read-only', 'DCB.DHCSR.S_HALT': 'read-only', 'DCB.DHCSR.S_SLEEP': 'read-only', 'DCB.DHCSR.S_LOCKUP': 'read-only',
    'DCB.DHCSR.S_SDE': 'read-only', 'DCB.DHCSR.S_NSUIDE': 'read-only', 'DCB.DHCSR.S_SUIDE': 'read-only', 'DCB.DHCSR.S_FPD': 'read-only',
    'DCB.DHCSR.S_RETIRE_ST': 'read-only', 'DCB.DHCSR.S_RESET_ST': 'read-only', 'DCB.DHCSR.S_RESTART_ST': 'read-only',
    'MPU.RBAR.VALID': 'write-only',
}

FIELD_WIDTH_OVERRIDES = {
    'DIB.DDEVARCH.PRESENT': 1,        # the header masks 5 bits; DEVARCH.PRESENT is bit 20 only
}

# Byte-wide or write-key aliases that overlap the bit fields; the register description says where they went.
DROP_FIELDS = {
    'SCB.CFSR.MEMFAULTSR', 'SCB.CFSR.BUSFAULTSR', 'SCB.CFSR.USGFAULTSR',
    'SCB.AIRCR.VECTKEYSTAT',
    'DCB.DHCSR.DBGKEY',
    'MPU.RASR.ATTRS',
}

# Architectural fields the headers do not define (they only define whole-register accessors).
EXTRA_FIELDS = {
    'NVIC.ISER': [('SETENA', 0, 32, 'Bit k: write 1 to enable IRQ 32n+k; reads 1 if enabled. Writing 0 has no effect.')],
    'NVIC.ICER': [('CLRENA', 0, 32, 'Bit k: write 1 to disable IRQ 32n+k; reads 1 if enabled. Writing 0 has no effect.')],
    'NVIC.ISPR': [('SETPEND', 0, 32, 'Bit k: write 1 to set IRQ 32n+k pending; reads 1 if pending.')],
    'NVIC.ICPR': [('CLRPEND', 0, 32, 'Bit k: write 1 to clear IRQ 32n+k pending; reads 1 if pending.')],
    'NVIC.IABR': [('ACTIVE', 0, 32, 'Bit k: 1 = the handler of IRQ 32n+k is active.')],
    'NVIC.ITNS': [('ITNS', 0, 32, 'Bit k: 1 = IRQ 32n+k targets Non-secure state, 0 = Secure.')],
    'SCB.MMFAR': [('ADDRESS', 0, 32, 'Data address of the MemManage fault (valid when CFSR.MMARVALID = 1).')],
    'SCB.BFAR': [('ADDRESS', 0, 32, 'Data address of the precise BusFault (valid when CFSR.BFARVALID = 1).')],
    'SCB.SFAR': [('ADDRESS', 0, 32, 'Address of the SecureFault (valid when SFSR.SFARVALID = 1).')],
    'SAU.SFAR': [('ADDRESS', 0, 32, 'Address of the SecureFault (valid when SFSR.SFARVALID = 1).')],
    'SCB.AFSR': [('IMPDEF', 0, 32, 'Implementation-defined auxiliary fault flags; write 1 to clear.')],
    'SCB.CPACR': [(f'CP{n}', 2 * n, 2, f'Access rights for coprocessor {n}: 0 = denied (NOCP UsageFault), 1 = privileged only, 3 = full access.') for n in range(8)] +
                 [('CP10', 20, 2, 'FPU/MVE access (CP10): 0 = denied — any FP instruction raises a NOCP UsageFault/HardFault, 1 = privileged only, 3 = full access. Must equal CP11.'),
                  ('CP11', 22, 2, 'FPU/MVE access (CP11): must be set identically to CP10.')],
    'SCB.ICIMVAU': [('ADDRESS', 0, 32, 'Any address inside the instruction cache line to invalidate.')],
    'SCB.DCIMVAC': [('ADDRESS', 0, 32, 'Any address inside the data cache line to invalidate.')],
    'SCB.DCCMVAU': [('ADDRESS', 0, 32, 'Any address inside the data cache line to clean to the point of unification.')],
    'SCB.DCCMVAC': [('ADDRESS', 0, 32, 'Any address inside the data cache line to clean to the point of coherency.')],
    'SCB.DCCIMVAC': [('ADDRESS', 0, 32, 'Any address inside the data cache line to clean and invalidate.')],
    'MPU.MAIR0': [(f'Attr{n}', 8 * n, 8, f'Memory attribute encoding {n}, selected by RLAR.AttrIndx: Device memory = 0b0000dd00 (dd: 00 nGnRnE, 01 nGnRE, 10 nGRE, 11 GRE); '
                                          'Normal memory = outer[7:4] inner[3:0] with 0100 non-cacheable, 10RW write-through, 11RW write-back (R = read-allocate, W = write-allocate; 1111 = write-back RWA).') for n in range(4)],
    'MPU.MAIR1': [(f'Attr{n}', 8 * (n - 4), 8, f'Memory attribute encoding {n}, selected by RLAR.AttrIndx (same encoding as MAIR0.Attr0).') for n in range(4, 8)],
}
