# Copyright 2026 Arm Limited
# Licensed under the Apache License, Version 2.0; see gen_core_svd.py.
"""CoreSight components in the core: DWT, ITM, TPIU, PMU, and the STAR-MC1 BPU.
Condensed from the ARMv7-M / ARMv8-M ARMs, the CoreSight Architecture Specification and the core TRMs."""

PERIPHERAL_DESC = {
    'DWT': 'Data Watchpoint and Trace unit: cycle counter and profiling counters, PC sampling, exception trace, and address/data comparators that '
           'raise watchpoints (halt or DebugMonitor), trigger the ETM/CTI or emit data trace. Needs DEMCR.TRCENA = 1.',
    'ITM': 'Instrumentation Trace Macrocell: 32 stimulus ports that software writes to emit printf-style trace over SWO/TPIU, plus timestamps '
           'and the DWT event/PC-sample packets. Needs DEMCR.TRCENA = 1, an unlocked LAR on ARMv7-M, TCR.ITMENA and the port enabled in TER.',
    'TPIU': 'Trace Port Interface Unit: drives the ITM/DWT/ETM trace out through the parallel trace port or the single-wire SWO pin (Manchester or UART/NRZ). '
            'ACPR sets the SWO baud rate, SPPR the pin protocol, FFCR the formatter.',
    'PMU': 'Performance Monitoring Unit (ARMv8.1-M): a 32-bit cycle counter and up to 8 (architecturally 31) 16-bit event counters selecting from the '
           'PMU event list (instructions, cache refills, branch mispredictions, MVE activity …), with overflow interrupt/halt.',
    'BPU': 'Breakpoint Unit (Flash Patch and Breakpoint unit FPBv2 on STAR-MC1): up to eight hardware instruction breakpoint comparators.',
}

REGISTER_DESC = {
    'DWT.CTRL': 'DWT Control Register: cycle counter, PC sampling, exception trace and profiling event enables; read-only capability bits (NUMCOMP, NOCYCCNT…) in the top byte.',
    'DWT.CYCCNT': 'Cycle Count Register: counts processor clock cycles while CTRL.CYCCNTENA = 1 (and DEMCR.TRCENA), wrapping at 2^32. Read for cycle-accurate timing; write to reset.',
    'DWT.CPICNT': 'CPI Count Register: extra cycles (beyond the first) of every instruction, 8-bit, generating a CPI event on overflow when CTRL.CPIEVTENA is set.',
    'DWT.EXCCNT': 'Exception Overhead Count Register: cycles spent in exception entry and exit, 8-bit, event on overflow.',
    'DWT.SLEEPCNT': 'Sleep Count Register: cycles spent sleeping, 8-bit, event on overflow.',
    'DWT.LSUCNT': 'LSU Count Register: extra cycles spent by load/store instructions, 8-bit, event on overflow.',
    'DWT.FOLDCNT': 'Folded-instruction Count Register: instructions that took zero cycles (folded), 8-bit, event on overflow.',
    'DWT.PCSR': 'Program Counter Sample Register: the address of a recently executed instruction — read repeatedly by a debugger for non-intrusive statistical profiling. 0xFFFFFFFF when halted.',
    'DWT.COMPn': 'Comparator Register n: the address (or data value / cycle count) that comparator n matches against, as configured in FUNCTIONn.',
    'DWT.MASKn': 'Mask Register n (ARMv7-M): number of low address bits ignored by comparator n, making it match a power-of-two range.',
    'DWT.FUNCTIONn': 'Function Register n: what comparator n compares (instruction address, data address, data value, cycle count) and what happens on a match '
                     '(watchpoint debug event, trace packet, CMPMATCH trigger). MATCHED reports a hit.',
    'DWT.DEVARCH': 'Device Architecture Register: CoreSight ARCHID of the DWT (0x1A02).',
    'DWT.DEVTYPE': 'Device Type Register: 0x00 (miscellaneous).',
    'ITM.STIMn': 'Stimulus Port n: a write emits an 8/16/32-bit software trace packet on port n (if enabled in TER). Reads return FIFOREADY, so software can wait for space.',
    'ITM.TER': 'Trace Enable Register: bit k enables stimulus port k. Privileged access only.',
    'ITM.TPR': 'Trace Privilege Register: which stimulus ports unprivileged code may write.',
    'ITM.TCR': 'Trace Control Register: ITM enable, timestamps, synchronization, DWT packet forwarding and the ATB source ID.',
    'ITM.ITREAD': 'Integration Test Read Register (integration mode only).',
    'ITM.ITWRITE': 'Integration Test Write Register (integration mode only).',
    'ITM.ITCTRL': 'Integration Mode Control Register: 1 = the ITM ATB outputs are driven from ITWRITE for topology testing.',
    'ITM.DEVARCH': 'Device Architecture Register: CoreSight ARCHID of the ITM (0x1A01).',
    'ITM.DEVTYPE': 'Device Type Register: 0x43 (trace source, processor).',
    'ITM.LAR': 'Lock Access Register: software must write 0xC5ACCE55 here before writing any other ITM register (ARMv7-M). Debugger accesses are never locked.',
    'ITM.LSR': 'Lock Status Register: whether the ITM registers are locked against software writes.',
    'TPIU.SSPSR': 'Supported Parallel Port Size Register: bit n−1 set = a trace port width of n bits is supported. Read-only.',
    'TPIU.CSPSR': 'Current Parallel Port Size Register: one-hot, bit n−1 = width n; must be 1 (bit 0) for SWO.',
    'TPIU.ACPR': 'Asynchronous Clock Prescaler Register: SWO baud rate = TRACECLKIN / (PRESCALER + 1).',
    'TPIU.SPPR': 'Selected Pin Protocol Register: parallel trace port, SWO Manchester or SWO NRZ (UART).',
    'TPIU.FFSR': 'Formatter and Flush Status Register.',
    'TPIU.FFCR': 'Formatter and Flush Control Register: enable continuous formatting (needed when the ETM and ITM share the port), manual flush, trigger indication.',
    'TPIU.FSCR': 'Formatter Synchronization Counter Register: how often the formatter inserts a synchronization sequence.',
    'TPIU.PSCR': 'Periodic Synchronization Control Register: how often the formatter inserts synchronization packets.',
    'TPIU.TRIGGER': 'Integration register: the current state of the TRIGIN input.',
    'TPIU.FIFO0': 'Integration Test FIFO Data 0: ETM data bytes and ATB valid/byte-count flags (integration mode).',
    'TPIU.FIFO1': 'Integration Test FIFO Data 1: ITM data bytes and ATB flags (integration mode).',
    'TPIU.ITFTTD0': 'Integration Test FIFO Test Data 0: ATB interface 1 (ETM) data bytes and handshake flags (integration mode).',
    'TPIU.ITFTTD1': 'Integration Test FIFO Test Data 1: ATB interface 2 (ITM) data bytes and handshake flags (integration mode).',
    'TPIU.ITATBCTR2': 'Integration Test ATB Control 2: ATREADY/AFVALID outputs to the ATB masters (integration mode).',
    'TPIU.ITATBCTR0': 'Integration Test ATB Control 0: ATVALID/AFREADY inputs from the ATB masters (integration mode).',
    'TPIU.ITCTRL': 'Integration Mode Control Register.',
    'TPIU.CLAIMSET': 'Claim Tag Set Register: read = which claim bits are implemented, write 1 = set a claim bit. Lets a debugger and software signal ownership of the TPIU.',
    'TPIU.CLAIMCLR': 'Claim Tag Clear Register: read = current claim tag, write 1 = clear a bit.',
    'TPIU.DEVID': 'Device Configuration Register: number of trace inputs, FIFO size and which pin protocols are supported. Read-only.',
    'TPIU.DEVTYPE': 'Device Type Register: 0x11 (trace sink, trace port). Read-only.',
    'PMU.EVCNTRn': 'Event Counter n: 16-bit count of the event selected in EVTYPERn. Only NUM_CNTS counters exist (8 on Cortex-M55/M85); the rest read as zero.',
    'PMU.CCNTR': 'Cycle Counter: 32-bit processor cycle count while CTRL.ENABLE = 1 and CYCCNT_DISABLE = 0.',
    'PMU.EVTYPERn': 'Event Type Register n: the event number counter n counts (see the PMU event list in the core TRM).',
    'PMU.CCFILTR': 'Cycle Counter Filter Register: reserved (no filtering on M-profile).',
    'PMU.CNTENSET': 'Count Enable Set Register: write 1 to enable a counter; reads the enable state of every counter.',
    'PMU.CNTENCLR': 'Count Enable Clear Register: write 1 to disable a counter; reads the enable state.',
    'PMU.INTENSET': 'Interrupt Enable Set Register: write 1 to enable the overflow interrupt/debug event of a counter; reads the enable state.',
    'PMU.INTENCLR': 'Interrupt Enable Clear Register: write 1 to disable the overflow interrupt of a counter.',
    'PMU.OVSCLR': 'Overflow Flag Status Clear Register: reads the overflow flags; write 1 to clear a flag.',
    'PMU.SWINC': 'Software Increment Register: write 1 to increment a counter that is counting the SW_INCR event (0x0000).',
    'PMU.OVSSET': 'Overflow Flag Status Set Register: reads the overflow flags; write 1 to set a flag (testing).',
    'PMU.TYPE': 'PMU Type Register: how many counters exist, their size, and which options are supported. Read-only.',
    'PMU.CTRL': 'PMU Control Register: global enable, counter resets, cycle counter disable, freeze/trace on overflow.',
    'PMU.AUTHSTATUS': 'Authentication Status Register: which debug/trace permissions currently apply to the PMU.',
    'PMU.DEVARCH': 'Device Architecture Register: CoreSight ARCHID of the PMU (0x0A06 with revision → 0x2A06).',
    'PMU.DEVTYPE': 'Device Type Register: 0x16 (performance monitor, processor core).',
    'BPU.CTRL': 'Breakpoint Control Register: enable and the number of comparators. Writes must set KEY.',
    'BPU.COMPn': 'Breakpoint Comparator n: halfword-aligned instruction address to break on.',
    'BPU.DEVARCH': 'Device Architecture Register: CoreSight ARCHID of the FPB (0x1A03).',
    'BPU.DEVTYPE': 'Device Type Register: 0x00.',
}

FIELD_DESC = {
    # ── DWT ──────────────────────────────────────────────────────────────────
    'DWT.CTRL.CYCCNTENA': 'Cycle counter enable: 1 = CYCCNT counts (DEMCR.TRCENA must be 1). Reset value 0.',
    'DWT.CTRL.POSTPRESET': 'Reload value for the POSTCNT down-counter that divides the CYCTAP rate for PC sampling and CYCEVT events (0 = every tap).',
    'DWT.CTRL.POSTINIT': 'Initial value of POSTCNT.',
    'DWT.CTRL.CYCTAP': 'CYCCNT tap that decrements POSTCNT: 0 = bit 6 (every 64 cycles), 1 = bit 10 (every 1024 cycles).',
    'DWT.CTRL.SYNCTAP': 'Synchronization packet interval (with TCR.SYNCENA): 0 = disabled, 1 = every 2^24 cycles (CYCCNT bit 24), 2 = 2^26, 3 = 2^28.',
    'DWT.CTRL.PCSAMPLENA': 'Periodic PC sample packets enable: a PC sample is emitted through the ITM every POSTCNT underflow (statistical profiling over SWO).',
    'DWT.CTRL.EXCTRCENA': 'Exception trace enable: emit packets on every exception entry, exit and return.',
    'DWT.CTRL.CPIEVTENA': 'Enable the CPI counter overflow event packet.',
    'DWT.CTRL.EXCEVTENA': 'Enable the exception overhead counter overflow event packet.',
    'DWT.CTRL.SLEEPEVTENA': 'Enable the sleep counter overflow event packet.',
    'DWT.CTRL.LSUEVTENA': 'Enable the LSU counter overflow event packet.',
    'DWT.CTRL.FOLDEVTENA': 'Enable the folded-instruction counter overflow event packet.',
    'DWT.CTRL.CYCEVTENA': 'Enable the POSTCNT underflow (cycle count) event packet.',
    'DWT.CTRL.CYCDISS': 'Cycle counter disabled in Secure state (ARMv8-M): 1 = CYCCNT does not count while the processor is in Secure state. Secure access only.',
    'DWT.CTRL.NOPRFCNT': '1 = the profiling counters (CPICNT, EXCCNT, SLEEPCNT, LSUCNT, FOLDCNT) are not implemented. Read-only.',
    'DWT.CTRL.NOCYCCNT': '1 = CYCCNT is not implemented. Read-only.',
    'DWT.CTRL.NOEXTTRIG': '1 = the CMPMATCH trigger outputs are not implemented. Read-only.',
    'DWT.CTRL.NOTRCPKT': '1 = trace sampling and exception tracing (PC samples, data trace, exception trace) are not implemented. Read-only.',
    'DWT.CTRL.NUMCOMP': 'Number of comparators implemented (0-15; 4 on most Cortex-M3/M4/M7/M33 devices). Read-only.',
    'DWT.CPICNT.CPICNT': 'Current CPI count (extra cycles per instruction), wraps at 256 with an event.',
    'DWT.EXCCNT.EXCCNT': 'Current exception overhead count, wraps at 256 with an event.',
    'DWT.SLEEPCNT.SLEEPCNT': 'Current sleep cycle count, wraps at 256 with an event.',
    'DWT.LSUCNT.LSUCNT': 'Current load/store extra-cycle count, wraps at 256 with an event.',
    'DWT.FOLDCNT.FOLDCNT': 'Current folded-instruction count, wraps at 256 with an event.',
    'DWT.MASK.MASK': 'Log2 of the number of low address bits ignored by the comparator (0 = exact match, 4 = 16-byte range …). The maximum supported value is found by writing all ones and reading back.',
    'DWT.FUNCTION.FUNCTION': 'ARMv7-M comparator function: 0 disabled; 1 emit PC sample on match, 2 emit data value, 3 emit PC and data value; 4 watchpoint on instruction fetch (PC), 5 watchpoint on read, '
                             '6 watchpoint on write, 7 watchpoint on read or write; 8-15 ETM trigger / data trace variants. With CYCMATCH: 1 = event, 4 = watchpoint on cycle count match.',
    'DWT.FUNCTION.EMITRANGE': '1 = emit data-trace address offset packets instead of the full address (data trace functions 1-3 and 12-15).',
    'DWT.FUNCTION.CYCMATCH': 'Comparator 0 only: 1 = compare CYCCNT against COMP0 instead of an address.',
    'DWT.FUNCTION.DATAVMATCH': '1 = compare the data value of the access (COMPn) rather than the address; DATAVADDR0/1 select the comparators that match the address.',
    'DWT.FUNCTION.LNK1ENA': 'Read-only: 1 = a second linked address comparator (DATAVADDR1) is supported for data value matching.',
    'DWT.FUNCTION.DATAVSIZE': 'Size of the data value to match: 0 = byte, 1 = halfword, 2 = word.',
    'DWT.FUNCTION.DATAVADDR0': 'Number of the comparator that supplies the address match for data-value matching (DATAVMATCH = 1).',
    'DWT.FUNCTION.DATAVADDR1': 'Number of the second linked address comparator (only if LNK1ENA = 1).',
    'DWT.FUNCTION.MATCHED': 'The comparator matched since this register was last read. Cleared on read.',
    'DWT.FUNCTION.MATCH': 'ARMv8-M match type: 0 disabled, 1 cycle counter (comparator 0), 2 instruction address, 3 instruction address limit (with the previous comparator forms a range), '
                          '4 data address, 5 data address limit, 6 data address with data value (linked to the next comparator), 7 data address limit with value, 8 data value, 9 data address linked (for the value in the next comparator), '
                          '10 data address with value linked, 11-15 further data-value/range combinations. See the ARMv8-M ARM DWT_FUNCTION table and ID for what this comparator supports.',
    'DWT.FUNCTION.ACTION': 'Action on match: 0 = trigger only (CMPMATCH to ETM/CTI), 1 = debug event (halt, or DebugMonitor), 2 = data trace packet (address/PC/value), 3 = both trace and trigger.',
    'DWT.FUNCTION.ID': 'Read-only capability ID of this comparator: which MATCH types (cycle counter, instruction address, data address, data value, linked/limit) it supports — see the DWT_FUNCTION.ID table in the ARMv8-M ARM.',
    # ── ITM ──────────────────────────────────────────────────────────────────
    'ITM.STIM.FIFOREADY': 'Read: 1 = the stimulus port can accept a write (FIFO not full), 0 = wait.',
    'ITM.STIM.DISABLED': 'Read: 1 = the port is disabled (TER bit clear, ITM disabled, or privilege violation) and writes are discarded.',
    'ITM.TPR.PRIVMASK': 'Bit k = 1: stimulus port group k is privileged-only (unprivileged writes are ignored). ARMv7-M: 4 groups of 8 ports; ARMv8-M: one bit per port.',
    'ITM.TCR.ITMENA': 'ITM enable. Clear before reconfiguring; wait for BUSY = 0 before disabling.',
    'ITM.TCR.TSENA': 'Local timestamp packets enable: a delta timestamp follows each group of packets.',
    'ITM.TCR.SYNCENA': 'Synchronization packets enable (rate from DWT.CTRL.SYNCTAP). Needed for the receiver to recover framing.',
    'ITM.TCR.DWTENA': 'Enable forwarding of DWT hardware event packets (PC samples, watchpoints, exception trace, counters) through the ITM (TXENA on ARMv8-M).',
    'ITM.TCR.SWOENA': 'Timestamp clock: 1 = the local timestamp counter runs from the (asynchronous) SWO clock, 0 = from the processor clock. Set with TSENA in SWO mode.',
    'ITM.TCR.STALLENA': 'Stall enable (ARMv8-M): 1 = a stimulus-port write to a full FIFO stalls the processor instead of being dropped, guaranteeing complete trace.',
    'ITM.TCR.TSPRESCALE': 'Local timestamp prescaler: 0 = none, 1 = divide by 4, 2 = by 16, 3 = by 64.',
    'ITM.TCR.GTSFREQ': 'Global timestamp frequency: 0 = disabled, 1 = every 128 cycles, 2 = every 8192 cycles, 3 = after every packet when the trace bus is idle.',
    'ITM.TCR.TRACEBUSID': 'ATB source ID of the ITM (must be unique and non-zero; 1 is conventional). The TPIU formatter tags packets with it when several sources share the port.',
    'ITM.TCR.BUSY': 'Read-only: 1 = the ITM is still processing events. Wait for 0 before disabling or changing the configuration.',
    'ITM.ITREAD.ATREADY': 'Integration: the ATREADY input from the ATB.',
    'ITM.ITREAD.AFVALID': 'Integration: the AFVALID (flush request) input.',
    'ITM.ITWRITE.ATREADY': 'Integration: drives the ITM ATVALID output (the header reuses the ITREAD names).',
    'ITM.ITWRITE.AFVALID': 'Integration: drives the ITM AFREADY output.',
    'ITM.ITCTRL.IME': 'Integration mode enable: 1 = the IT* registers control the ATB signals for topology detection; 0 = normal operation.',
    'ITM.LSR.PRESENT': 'Software lock implemented (1 on ARMv7-M cores).',
    'ITM.LSR.ACCESS': 'Lock status: 1 = locked, software writes to the ITM are ignored until 0xC5ACCE55 is written to LAR.',
    'ITM.LSR.BYTEACC': '0 = the lock register is accessed as a 32-bit word.',
    # ── TPIU ─────────────────────────────────────────────────────────────────
    'TPIU.ACPR.PRESCALER': 'SWO clock divider: baud rate = TRACECLKIN / (PRESCALER + 1). For example 4 MHz SWO from 200 MHz: PRESCALER = 49.',
    'TPIU.SPPR.TXMODE': 'Pin protocol: 0 = parallel trace port, 1 = SWO Manchester, 2 = SWO NRZ (UART-like, the common choice), 3 = reserved.',
    'TPIU.FFSR.FlInProg': 'Flush in progress.',
    'TPIU.FFSR.FtStopped': 'Formatter stopped (RAZ on cores whose formatter cannot stop).',
    'TPIU.FFSR.TCPresent': 'TRACECTL pin present: 1 = the trace port has a TRACECTL signal.',
    'TPIU.FFSR.FtNonStop': 'Formatter cannot be stopped (reads 1).',
    'TPIU.FFCR.EnFCont': 'Enable continuous formatting: 1 = frames are always formatted with source IDs (required when the ETM and ITM share the trace port; must be 0 for ITM-only SWO to get raw ITM packets).',
    'TPIU.FFCR.FOnMan': 'Manual flush: write 1 to flush the formatter FIFO now.',
    'TPIU.FFCR.TrigIn': 'Indicate a trigger on the TRIGIN input in the formatted stream (reads 1).',
    'TPIU.PSCR.PSCount': 'Periodic synchronization: 0 = disabled; else a synchronization sequence is inserted every 2^PSCount bytes (minimum 7 = 128 bytes).',
    'TPIU.TRIGGER.TRIGGER': 'Current state of the TRIGIN input.',
    'TPIU.FIFO.ETM0': 'ETM ATB data byte 0.',
    'TPIU.FIFO.ETM1': 'ETM ATB data byte 1.',
    'TPIU.FIFO.ETM2': 'ETM ATB data byte 2.',
    'TPIU.FIFO.ETM_bytecount': 'Number of valid ETM bytes − 1.',
    'TPIU.FIFO.ETM_ATVALID': 'ETM ATVALID.',
    'TPIU.FIFO.ITM_bytecount': 'Number of valid ITM bytes − 1.',
    'TPIU.FIFO.ITM_ATVALID': 'ITM ATVALID.',
    'TPIU.FIFO.ITM0': 'ITM ATB data byte 0.',
    'TPIU.FIFO.ITM1': 'ITM ATB data byte 1.',
    'TPIU.FIFO.ITM2': 'ITM ATB data byte 2.',
    'TPIU.ITFTTD.ATB_IF1_data0': 'ATB interface 1 data byte 0.',
    'TPIU.ITFTTD.ATB_IF1_data1': 'ATB interface 1 data byte 1.',
    'TPIU.ITFTTD.ATB_IF1_data2': 'ATB interface 1 data byte 2.',
    'TPIU.ITFTTD.ATB_IF1_bytecount': 'ATB interface 1 valid bytes − 1.',
    'TPIU.ITFTTD.ATB_IF1_ATVALID': 'ATB interface 1 ATVALID.',
    'TPIU.ITFTTD.ATB_IF2_bytecount': 'ATB interface 2 valid bytes − 1.',
    'TPIU.ITFTTD.ATB_IF2_ATVALID': 'ATB interface 2 ATVALID.',
    'TPIU.ITFTTD.ATB_IF2_data0': 'ATB interface 2 data byte 0.',
    'TPIU.ITFTTD.ATB_IF2_data1': 'ATB interface 2 data byte 1.',
    'TPIU.ITFTTD.ATB_IF2_data2': 'ATB interface 2 data byte 2.',
    'TPIU.ITATBCTR.ATREADY1S': 'ATB interface 1 ATREADY (integration).',
    'TPIU.ITATBCTR.AFVALID1S': 'ATB interface 1 AFVALID (integration).',
    'TPIU.ITATBCTR.ATREADY2': 'ATB interface 2 ATREADY (integration).',
    'TPIU.ITATBCTR.ATREADY1': 'ATB interface 1 ATREADY (integration).',
    'TPIU.ITATBCTR.ATVALID1': 'ATB interface 1 ATVALID (integration).',
    'TPIU.ITATBCTR.ATVALID2': 'ATB interface 2 ATVALID (integration).',
    'TPIU.ITATBCTR.AFREADY1': 'ATB interface 1 AFREADY (integration).',
    'TPIU.ITATBCTR.AFREADY2': 'ATB interface 2 AFREADY (integration).',
    'TPIU.ITCTRL.Mode': 'Integration mode: 0 = normal operation, 1 = integration test mode (the IT* registers drive/observe the ATB and trace port).',
    'TPIU.CLAIMSET.SET': 'Read: 1 = claim bit implemented; write 1 = set the claim bit.',
    'TPIU.CLAIMCLR.CLR': 'Read: current claim tag; write 1 = clear the claim bit.',
    'TPIU.DEVID.NrTraceInput': 'Number of ATB trace inputs (implementation-defined encoding, see the core TRM; Cortex-M cores with an ETM have two: ETM and ITM).',
    'TPIU.DEVID.AsynClkIn': '1 = a separate asynchronous SWO clock input (TRACECLKIN) is present.',
    'TPIU.DEVID.FIFOSZ': 'Formatter FIFO size, log2 of the number of words (2 = 4 words on Cortex-M33/M55).',
    'TPIU.DEVID.MinBufSz': 'Minimum input buffer size, log2 words (2 = 4 words on Cortex-M3/M4/M7).',
    'TPIU.DEVID.PTINVALID': '1 = the parallel trace port is NOT supported (SWO only).',
    'TPIU.DEVID.MANCVALID': '1 = SWO Manchester encoding is supported.',
    'TPIU.DEVID.NRZVALID': '1 = SWO NRZ (UART) encoding is supported.',
    'TPIU.DEVTYPE.MajorType': 'Major type: 1 = trace sink.',
    'TPIU.DEVTYPE.SubType': 'Sub type: 1 = trace port (TPIU).',
    # ── PMU ──────────────────────────────────────────────────────────────────
    'PMU.EVCNTR.CNT': 'Event count (16 bits on Cortex-M55/M85; an overflow sets OVSSET bit n).',
    'PMU.EVTYPER.EVENTTOCNT': 'Event number to count. Common events: 0x0000 SW_INCR, 0x0001 L1I_CACHE_REFILL, 0x0003 L1D_CACHE_REFILL, 0x0004 L1D_CACHE, 0x0008 INST_RETIRED, 0x0010 BR_MIS_PRED, '
                              '0x0011 CPU_CYCLES, 0x0012 BR_PRED, 0x0014 L1I_CACHE, 0x0023 STALL_FRONTEND, 0x0024 STALL_BACKEND, 0x0100-0x01xx MVE_* (see the core TRM).',
    'PMU.TYPE.NUM_CNTS': 'Number of event counters implemented (8 on Cortex-M55/M85/M52).',
    'PMU.TYPE.SIZE_CNTS': 'Event counter size − 1 in bits (15 = 16-bit counters).',
    'PMU.TYPE.CYCCNT_PRESENT': '1 = the cycle counter CCNTR is implemented.',
    'PMU.TYPE.FRZ_OV_SUPPORT': '1 = freeze-on-overflow (CTRL.FRZ_ON_OV) is supported.',
    'PMU.TYPE.TRACE_ON_OV_SUPPORT': '1 = trace-on-overflow (CTRL.TRACE_ON_OV) is supported.',
    'PMU.CTRL.ENABLE': 'Global enable: 0 = all counters stop (their values are kept).',
    'PMU.CTRL.EVENTCNT_RESET': 'Write 1 to reset every event counter to 0. Reads as 0.',
    'PMU.CTRL.CYCCNT_RESET': 'Write 1 to reset CCNTR to 0. Reads as 0.',
    'PMU.CTRL.CYCCNT_DISABLE': '1 = the cycle counter is disabled even when ENABLE = 1.',
    'PMU.CTRL.FRZ_ON_OV': 'Freeze on overflow: 1 = all counters stop when any counter overflows, so a snapshot can be read.',
    'PMU.CTRL.TRACE_ON_OV': 'Trace on overflow: 1 = a counter overflow emits a trace (ITM/ETM) event.',
    'PMU.AUTHSTATUS.NSID': 'Non-secure invasive debug: 2 = disabled, 3 = enabled.',
    'PMU.AUTHSTATUS.NSNID': 'Non-secure non-invasive debug: 2 = disabled, 3 = enabled. Counting Non-secure events requires it.',
    'PMU.AUTHSTATUS.SID': 'Secure invasive debug: 2 = disabled, 3 = enabled.',
    'PMU.AUTHSTATUS.SNID': 'Secure non-invasive debug: 2 = disabled, 3 = enabled. Counting Secure events requires it.',
    'PMU.AUTHSTATUS.NSUID': 'Non-secure unprivileged invasive debug: 2 = disabled, 3 = enabled.',
    'PMU.AUTHSTATUS.NSUNID': 'Non-secure unprivileged non-invasive debug: 2 = disabled, 3 = enabled.',
    'PMU.AUTHSTATUS.SUID': 'Secure unprivileged invasive debug: 2 = disabled, 3 = enabled.',
    'PMU.AUTHSTATUS.SUNID': 'Secure unprivileged non-invasive debug: 2 = disabled, 3 = enabled.',
    # ── BPU (STAR-MC1) ───────────────────────────────────────────────────────
    'BPU.CTRL.ENABLE': 'Breakpoint unit enable.',
    'BPU.CTRL.KEY': 'Write 1 to enable writes to this register; reads as 0.',
    'BPU.CTRL.NUM_CODE_L': 'Number of instruction address comparators, bits [3:0].',
    'BPU.CTRL.NUM_LIT': 'Number of literal comparators.',
    'BPU.CTRL.NUM_CODE_H': 'Number of instruction address comparators, bits [6:4].',
    'BPU.CTRL.REV': 'FPB architecture revision: 1 = FPBv2.',
    'BPU.COMP.BE': 'Breakpoint enable.',
    'BPU.COMP.BPADDR': 'Instruction address bits [31:1] to break on.',
}

import re as _re
PATTERN_FIELD_DESC = [
    (_re.compile(r'PMU\.CNTENSET\.CNT(\d+)_ENABLE'), 'Event counter {0}: write 1 to enable; reads 1 if enabled.'),
    (_re.compile(r'PMU\.CNTENSET\.CCNTR_ENABLE'), 'Cycle counter: write 1 to enable; reads 1 if enabled.'),
    (_re.compile(r'PMU\.CNTENCLR\.CNT(\d+)_ENABLE'), 'Event counter {0}: write 1 to disable; reads 1 if enabled.'),
    (_re.compile(r'PMU\.CNTENCLR\.CCNTR_ENABLE'), 'Cycle counter: write 1 to disable; reads 1 if enabled.'),
    (_re.compile(r'PMU\.INTENSET\.CNT(\d+)_ENABLE'), 'Event counter {0}: write 1 to enable its overflow interrupt (PMU_IRQ) / debug event; reads 1 if enabled.'),
    (_re.compile(r'PMU\.INTENSET\.CYCCNT_ENABLE'), 'Cycle counter: write 1 to enable its overflow interrupt; reads 1 if enabled.'),
    (_re.compile(r'PMU\.INTENCLR\.CNT(\d+)_ENABLE'), 'Event counter {0}: write 1 to disable its overflow interrupt; reads 1 if enabled.'),
    (_re.compile(r'PMU\.INTENCLR\.CYCCNT_ENABLE'), 'Cycle counter: write 1 to disable its overflow interrupt; reads 1 if enabled.'),
    (_re.compile(r'PMU\.OVSCLR\.CNT(\d+)_STATUS'), 'Event counter {0} overflowed; write 1 to clear the flag.'),
    (_re.compile(r'PMU\.OVSCLR\.CYCCNT_STATUS'), 'Cycle counter overflowed; write 1 to clear the flag.'),
    (_re.compile(r'PMU\.OVSSET\.CNT(\d+)_STATUS'), 'Event counter {0} overflow flag; write 1 to set it.'),
    (_re.compile(r'PMU\.OVSSET\.CYCCNT_STATUS'), 'Cycle counter overflow flag; write 1 to set it.'),
    (_re.compile(r'PMU\.SWINC\.CNT(\d+)'), 'Write 1 to increment event counter {0} if it counts SW_INCR (event 0x0000).'),
    (_re.compile(r'MPU\.MAIR\d?\.Attr(\d)'), 'Memory attribute encoding {0}, selected by RLAR.AttrIndx: Device memory = 0b0000dd00 (dd: 00 nGnRnE, 01 nGnRE, 10 nGRE, 11 GRE); '
                                             'Normal memory = outer[7:4] inner[3:0] with 0100 non-cacheable, 10RW write-through, 11RW write-back (R = read-allocate, W = write-allocate; 1111 = write-back RWA).'),
]

ENUMS = {
    'TPIU.SPPR.TXMODE': [('Parallel', 0, 'Parallel trace port'), ('SWO_Manchester', 1, 'Serial wire output, Manchester encoding'), ('SWO_NRZ', 2, 'Serial wire output, NRZ (UART) encoding')],
    'ITM.TCR.TSPRESCALE': [('None', 0, 'No prescaling'), ('Div4', 1, 'Divide by 4'), ('Div16', 2, 'Divide by 16'), ('Div64', 3, 'Divide by 64')],
    'DWT.FUNCTION.ACTION': [('Trigger', 0, 'CMPMATCH trigger only'), ('DebugEvent', 1, 'Watchpoint debug event'), ('Trace', 2, 'Data trace packet'), ('TraceTrigger', 3, 'Trace and trigger')],
}

RESET_VALUES = {}
REGISTER_ACCESS = {}
FIELD_ACCESS = {
    'DWT.CTRL.NOPRFCNT': 'read-only', 'DWT.CTRL.NOCYCCNT': 'read-only', 'DWT.CTRL.NOEXTTRIG': 'read-only', 'DWT.CTRL.NOTRCPKT': 'read-only', 'DWT.CTRL.NUMCOMP': 'read-only',
    'DWT.FUNCTION.LNK1ENA': 'read-only', 'DWT.FUNCTION.ID': 'read-only',
    'ITM.TCR.BUSY': 'read-only',
}
FIELD_WIDTH_OVERRIDES = {
    'TPIU.ITFTTD.ATB_IF1_ATVALID': 1,     # header masks 2 bits; the ATVALID flags are single bits at 26 and 29
    'TPIU.ITFTTD.ATB_IF2_ATVALID': 1,
}
DROP_FIELDS = {
    'TPIU.ITATBCTR.ATREADY2S', 'TPIU.ITATBCTR.AFVALID2S',   # duplicated at the same bits as the *1S names in the header
}
EXTRA_FIELDS = {
    'DWT.CYCCNT': [('CYCCNT', 0, 32, 'Cycle count. Writable; write 0 to restart a measurement.')],
    'DWT.PCSR': [('EIASAMPLE', 0, 32, 'Sampled instruction address (0xFFFFFFFF when the processor is halted or PCSR is not implemented).')],
    'DWT.COMP': [('COMP', 0, 32, 'Reference value for the comparator: an address, a data value (DATAVMATCH / MATCH = data value) or a cycle count.')],
    'ITM.STIM': [('FIFOREADY', 0, 1, 'Read: 1 = the stimulus port can accept a write (FIFO not full), 0 = wait.')],
    'ITM.TER': [('STIMENA', 0, 32, 'Bit k: stimulus port 32n+k enabled.')],
    'ITM.LAR': [('KEY', 0, 32, 'Write 0xC5ACCE55 to unlock the ITM registers for software writes; any other value locks them.')],
    'DWT.LAR': [('KEY', 0, 32, 'Write 0xC5ACCE55 to unlock the DWT registers for software writes; any other value locks them.')],
    'DWT.LSR': [('SLI', 0, 1, 'Software lock implemented.'), ('SLK', 1, 1, 'Locked: 1 = software writes are ignored.'), ('nTT', 2, 1, '0 = 32-bit lock access.')],
    'TPIU.SSPSR': [('SWIDTH', 0, 32, 'Bit n−1 set = a trace port width of n bits is supported.')],
    'TPIU.CSPSR': [('CWIDTH', 0, 32, 'One-hot current port width: bit n−1 = n bits. 1 = single-bit (SWO).')],
    'TPIU.FSCR': [('CycCount', 0, 12, 'Formatter synchronization interval in cycles (0 = disabled). See the CoreSight TPIU specification.')],
    'PMU.CCNTR': [('CCNT', 0, 32, 'Cycle count.')],
}
